# 11. 피벗과 언피벗
## 11.1 피벗 테이블
원시 데이터는 여러 가지 열로 다양한 특성을 보유하고, 이러한 특성을 기반으로 원시 데이터를 다각도로 요약할 수 있음\
피벗 테이블(pivot table)은 원시 데이터를 다양한 속성으로 요약한 표이며, 판다스도 피벗 테이블을 생성함

### 11.1.1 피벗 테이블을 사용하는 이유
원시 데이터의 행은 개별 사례이며, 열은 특성(feature)\
원시 데이터는 데이터를 추가해 관리하기 쉬운 장점이 있지만 원시 데이터만으로는 데이터의 의미 파악이 어려움\
피벗 테이블은 원시 데이터를 특성별로 그룹화해서 집계한 테이블임\
원시 데이터와 피벗 테이블은 부족한 부분을 서로 채워주는 상호 보완의 관계이므로 반드시 병행하여 사용

### 11.1.2 피벗 테이블과 집계 함수
피벗 테이블은 원시 데이터를 특성으로 그룹을 나누어 각각의 셀에 요약함\
피벗 테이블은 원시 데이터를 그룹별로 하나의 셀에 요약하기에 차원을 축소하는 집계 함수가 필요함\
집계 함수는 차원 축소 함수인데, 평균, 표준편차 등의 함수뿐만 아니라 차원을 축소하는 함수는 모두 넓은 의미에서 집계 함수에 포함됨\
원시 데이터는 대부분 하나의 그룹에 많은 개수의 데이터가 있으며, 요약하려면 그룹의 값을 하나로 차원 축소하는 집계 함수가 필요함

### 11.1.3 피벗 테이블 생성하기
판다스 pivot_table\
원시 데이터로 피벗 테이블을 생성하는 함수
```py
pivot_table 함수의 주요 매개변수와 인수, 기본값
df.pivot_table(values=None, index=None, columns=None, aggfunc='mean')
```
* values : 집계할 대상 열을 지정함
* index : 행으로 구분할 그룹을 나누는 기준 열을 지정함
* columns : 열로 구분할 그룹을 나누는 기준 열을 지정함
* aggfunc : 그룹의 차원 축소할 집계 함수를 지정함

In [1]:
import pandas as pd
# pd.options.display.float_format = '{:.1f}'.format # 소수점 첫째 자리 출력
data = [['김판다', '남', 'A', 97, '1등', '수시'],
        ['강승주', '여', 'A', 88, '2등', '정시'],
        ['권보아', '여', 'A', 78, '3등', '정시'],
        ['조민영', '여', 'B', 64, '3등', '수시'],
        ['박상현', '남', 'B', 84, '2등', '수시'],
        ['송중기', '남', 'B', 89, '1등', '수시'],
        ['최진환', '남', 'C', 87, '3등', '정시'],
        ['장범준', '남', 'C', 92, '2등', '정시'],
        ['안지선', '여', 'C', 99, '1등', '수시']]
col = ['이름', '성별', '반', '점수', '반등수', '비고']

data1 = {'제품': ['A', 'B', 'A', 'B', 'B', 'A'],
         '판매량': [float('nan'), 2, 3, 4, float('nan'), 6]}

df = pd.DataFrame(data, columns=col)
df1 = pd.DataFrame(data1)
df

    이름 성별  반  점수 반등수  비고
0  김판다  남  A  97  1등  수시
1  강승주  여  A  88  2등  정시
2  권보아  여  A  78  3등  정시
3  조민영  여  B  64  3등  수시
4  박상현  남  B  84  2등  수시
5  송중기  남  B  89  1등  수시
6  최진환  남  C  87  3등  정시
7  장범준  남  C  92  2등  정시
8  안지선  여  C  99  1등  수시

df를 반과 성별로 나누어 평균 점수를 피벗 테이블로 만들자\
pivot_table 함수의 주요 매개변수
1. values : 집계 대상
2. index : 행으로 구분할 그룹
3. columns : 열로 구분할 그룹
4. aggfunc : 집계 함수

values에는 집계할 대상인 열을 입력해야 함\
df의 반과 성별로 나누어 평균 점수를 구할 것이기에 집계 대상은 점수 열

그룹 구분 기준이 되는 열을 index와 ㅊolumns에 지정해야 함\
피벗 테이블의 행에서 반을 구분하고 열에서 남녀를 구분할 것이기에 index에 반, columns에 성별을 입력함

aggfunc은 반과 성별로 나누어 평균 점수를 피벗 테이블로 생성할 것이므로 집계함수에 mean을 입력함

In [2]:
df.pivot_table(values='점수', index='반', columns='성별', aggfunc='mean')

성별     남     여
반
A   97.0  83.0
B   86.5  64.0
C   89.5  99.0

### 11.1.4 복수의 인수를 입력해 피벗 테이블 생성하기
pivot_table 함수의 네 가지 매개변수는 모두 복수의 인수를 입력할 수 있으며 입력할 인수를 리스트로 묶어 입력함\
index에 '반'과 '성별'을 리스트로 묶어 입력하고, columns에 '비고'를 지정

In [3]:
df.pivot_table(values='점수', index=['반','성별'], columns='비고')

비고      수시    정시
반 성별
A 남   97.0   NaN
  여    NaN  83.0
B 남   86.5   NaN
  여   64.0   NaN
C 남    NaN  89.5
  여   99.0   NaN

매개변수 index에 복수의 열을 입력해 피벗 테이블로 멀티 인덱스를 보유한 데이터 프레임을 반환함\
그룹에 해당하는 데이터가 존재하지 않는 셀은 NaN을 반환함\
이번에는 복수의 집계 함수를 사용하자

In [4]:
df.pivot_table('점수',index='반', columns='성별', aggfunc=['mean','count'])

    mean       count
성별     남     여     남  여
반
A   97.0  83.0     1  2
B   86.5  64.0     2  1
C   89.5  99.0     2  1

복수의 인수를 입력하면 멀티 인덱스를 보유한 데이터 프레임을 반환할 때가 많으니 멀티 인덱스를 다뤄야 함

### 11.1.5 인수로 함수를 입력하는 방법
pivot_table 함수는 차원 축소를 하고자 집계 함수를 입력해야 하기에 함수를 인수로 입력하는 방법에 대해 살펴볼 것임\
판다스에서는 pivot_table 함수뿐 아니라 apply 함수 등 인수로 함수를 입력해야 할 때가 자주 발생하는데 이 방법으로 함수를 입력함
1. 대상에 적용되는 함수를 입력함\
pivot_table 함수에 인수로 입력하는 집계 함수는 시리즈가 적용 대상인 함수여야 함\
시리즈에 적용되는 함수라면 사용자 정의 함수와 lambda 함수도 입력할 수 있음\
시리즈에 apply를 사용할 때는 셀에 적용되는 함수, 데이터 프레임에 apply를 사용할 때는 시리즈에 적용되는 함수를 인수로 입력해야 함
2. 메서드가 아닌 함수 형태로 입력함\
함수를 인수로 입력하기에 메서드가 아닌 함수를 입력해야 함\
null이 아닌 값의 개수를 세는 함수는 pd.Series.count인데 시리즈에 적용할 때는 s.count()의 형태로 메서드에 사용하지만 인수로 입력할 때는 함수 형태인 pd.Series.count로 입력해야 함
3. 자주 쓰이는 함수는 문자열로 해당 함수를 호출할 수 있으니 문자열을 입력함\
'count', 'sum', 'max', 'first', 'last' 등ㅇ의 많은 함수를 문자열로 입력함

### 11.1.6 그룹화에만 적용되는 집계 함수(first, last)
일반적으로 pivot_table에 쓰이는 집계 함수는 일반적인 통계 함수이며 대부분 시리즈에도 적용이 가능함\
하지만 first 함수, last 함수는 pivot_table 함수 혹은 groupby 함수처럼 그룹을 나누는 함수와 함께 사용할 때만 사용이 가능함

In [5]:
df1

  제품  판매량
0  A  NaN
1  B  2.0
2  A  3.0
3  B  4.0
4  B  NaN
5  A  6.0

In [6]:
df1.pivot_table('판매량', index='제품', aggfunc='first')

    판매량
제품
A   3.0
B   2.0

In [7]:
df1.pivot_table('판매량', index='제품', aggfunc='last')

    판매량
제품
A   6.0
B   4.0

In [8]:
(df.sort_values('점수', ascending=False)
 .pivot_table('이름', index='반', columns='성별', aggfunc='first')
)

성별    남    여
반
A   김판다  강승주
B   송중기  조민영
C   장범준  안지선

### 11.1.7 문자열 피벗
판다스 pivot\
집계 함수 없이 피벗 테이블을 만드는 함수로 주로 문자열 피벗에 쓰임
```py
pivot 함수의 주요 매개변수와 인수, 기본값
df.pivot(index=None, columns=None, values=None)
```
pivot_table 함수에 first, last와 같은 특정 집계 함수를 지정해 문자열 피벗을 수행하기도 하나, 통상 pivot 함수를 사용해 문자열의 피벗을 수행함\
pivot_table 함수에서 집계 함수가 필요했던 이유는 여러 개의 데이터가 하나의 그룹에 소속되어 차원을 축소해야 했기 때문\
모든 그룹에 각각 하나의 데이터만 소속된다면 집계 함수가 필요하지 않으며 이때 사용하는 함수가 pivot 함수\
집계 함수 없이 사용하기에 반드시 하나의 그룹에는 둘 이상의 데이터가 소속되지 않아야 하며, 만약 소속된 데이터가 2개 이상인 그룹이 존재하면 ValueError가 발생함

In [9]:
df.pivot(index='반', columns='반등수', values='이름')

반등수   1등   2등   3등
반
A    김판다  강승주  권보아
B    송중기  박상현  조민영
C    안지선  장범준  최진환

### 11.1.8 빈도수를 집계하는 교차표 생성하기(crosstab)
판다스 crosstab\
빈도수를 집계해 교차표를 생성하는 함수

In [10]:
data = {'반': ['A', 'A', 'A', 'B', 'B', 'B'],
        '성별': ['남', '여', '여', '여', '남', '남']}
df = pd.DataFrame(data)
df

   반 성별
0  A  남
1  A  여
2  A  여
3  B  여
4  B  남
5  B  남

기본적으로 빈도수는 value_counts 함수로 집계하며, pivot_table 함수의 집계 함수로 count 함수를 사용하여 집계하기도 함\
value_counts는 교차표가 아닌 시리즈를 생성하며, pivot_table 함수로 빈도수를 집계해 교차표를 생성하려면 최소 세 개의 열을 지정\
따라서 위처럼 열이 2개뿐일 때 pivot_table 함수를 사용하여 빈도수를 파악하려면 의미 없는 집계용 열을 추가해야 함\
이때 사용하는 함수가 crosstab 함수이며, crosstab 함수는 메서드로 사용할 수 없고 반드시 함수 pd.crosstab 형태로 사용해야 함

In [11]:
pd.crosstab(df['반'],df['성별'])

성별  남  여
반
A   1  2
B   2  1

## 11.2 언피벗
언피벗은 피벗의 반대이며 언피벗을 수행하면 원시 데이터처럼 개별 사례인 행과 특성인 열을 가진 데이터 구조로 변환됨

### 11.2.1 언피벗이 필요한 이유
원시 데이터는 데이터 추가 및 관리에 편리하고 피벗 테이블은 데이터 의미 파악에 용이함\
각자 장점이 있으므로 역할에 맞게 활용하고 서로 보완해야 하지만 실무 데이터는 그렇지 않을 때가 많음\
원시 데이터는 무겁고 다루기 어려워 피벗 테이블만 남겨서 사실상 피벗 테이블로 데이터를 관리할 때가 많음\
하지만 피벗 테이블에서 새로운 피벗 테이블을 만드는 것은 쉽지 않기에 원시 데이터도 필요함\
원시 데이터가 있다면 새로운 피벗 테이블을 쉽게 만들 수 있지만 원시 데이터는 무겁고 다루기 힘들기에 필요한 것이 언피벗

언피벗은 피벗의 반대이며, 피벗 테이블을 원시 데이터와 유사한 구조의 데이터로 만드는 작업\
원시 데이터가 보존되지 않은 때는 언피벗으로 피벗 테이블을 원시 데이터와 유사한 데이터로 변환함\
언피벗을 수행하면 원시 데이터의 장점을 그대로 계승하기에 데이터의 추가도 수월함\
언피벗을 하면 원시 데이터와 같은 형태의 구조가 되어 행 추가만 해도 손쉽게 개별 사례들을 추가하고, 새로운 열을 추가하는 것으로 새로운 특성을 생성함

판다스는 크게 두 가지 방법으로 언피벗을 수행함\
첫째, stack 함수와 reset_index 함수를 조합하여 언피벗을 수행함\
둘째, melt 함수로 언피벗을 수행함

### 11.2.2 stack 함수로 언피벗

In [12]:
import pandas as pd
data1 = {'1등': {'1회차': '김판다', '2회차': '박효신', '3회차': '김판다'},
         '2등': {'1회차': '권보아', '2회차': '권보아', '3회차': '박효신'},
         '3등': {'1회차': '박효신', '2회차': '강승주', '3회차': '김범수'}}
df = pd.DataFrame(data1)
df

      1등   2등   3등
1회차  김판다  권보아  박효신
2회차  박효신  권보아  강승주
3회차  김판다  박효신  김범수

stack은 앞서 다룬 멀티 인덱스에 활용하는 함수로 언피벗을 위한 함수는 아니지만 언피벗에 활용함\
언피벗된 상태는 데이터가 하나의 열로 늘어선 상태인데 ㄴtack을 해도 시리즈가 되면서 데이터가 한 줄로 늘어섬\
이때 reset_index로 인덱스를 모두 열로 만들면 언피벗된 데이터 프레임이 됨

In [13]:
df.stack()

1회차  1등    김판다
     2등    권보아
     3등    박효신
2회차  1등    박효신
     2등    권보아
     3등    강승주
3회차  1등    김판다
     2등    박효신
     3등    김범수
dtype: object

In [15]:
df.stack().reset_index()

  level_0 level_1    0
0     1회차      1등  김판다
1     1회차      2등  권보아
2     1회차      3등  박효신
3     2회차      1등  박효신
4     2회차      2등  권보아
5     2회차      3등  강승주
6     3회차      1등  김판다
7     3회차      2등  박효신
8     3회차      3등  김범수

In [17]:
df1 = df.stack().reset_index().set_axis(['회차','등수','이름'], axis=1)
df1

    회차  등수   이름
0  1회차  1등  김판다
1  1회차  2등  권보아
2  1회차  3등  박효신
3  2회차  1등  박효신
4  2회차  2등  권보아
5  2회차  3등  강승주
6  3회차  1등  김판다
7  3회차  2등  박효신
8  3회차  3등  김범수

언피벗을 수행하였으니 df1으로 새로운 피벗 테이블을 만들 것인데, 각 사람의 등수의 빈도수를 집계할 것임\
pivot_table 함수의 count도 가능하지만 빈도수를 집계하는 것이기에 crosstab 함수를 사용하는 것이 더 간편함

In [24]:
pd.crosstab(df1['이름'],df1['등수'])

등수   1등  2등  3등
이름
강승주   0   0   1
권보아   0   2   0
김범수   0   0   1
김판다   2   0   0
박효신   1   1   1

### 11.2.3 melt 함수로 언피벗
판다스 melt\
데이터 프레임의 언피벗을 수행하는 함수
```py
df.melt(id_vars=None, value_vars=None, var_name='variable', value_name='value')
```
* id_vars : 인덱스처럼 언피벗하지 않고 별도의 열로 처리될 열을 지정함
* value_vars : 언피벗을 수행할 열을 지정하며 기본값으로 id_vars에 지정되지 않은 모든 열을 언피벗함
* var_name : 언피벗 후 생성되는 variable 열의 이름을 변경함
* value_name : 언피벗 후 생성되는 value 열의 이름을 변경함

In [25]:
import pandas as pd
data = {'반': ['A', 'B', 'C'], '남': [10, 20, 15], '여': [30, 40, 35]}
df = pd.DataFrame(data)
df1 = df.set_index('반')
df

   반   남   여
0  A  10  30
1  B  20  40
2  C  15  35

df의 반 열은 언피벗 대상이 아니기에 인덱스로 설정되어야 함\
하지만 반 열이 일반 열로 설정되어 있기에 stack 함수로 df의 언피벗을 수행하려면 반 열을 인덱스로 설정하고 언피벗을 수행해야 함

melt 함수는 stack 함수로 언피벗할 때의 인덱스처럼 언피벗을 수행하지 않을 열을 지정할 수 있음\
매개변수 id_vars에 '반'을 입력하면 반 열의 데이터는 제외하고 나머지 데이터가 언피벗됨\
언피벗을 수행할 열은 value_vars에 지정하는데 남,여 열 모두 언피벗을 수행

In [26]:
df.melt('반', value_vars=['남','여'])

   반 variable  value
0  A        남     10
1  B        남     20
2  C        남     15
3  A        여     30
4  B        여     40
5  C        여     35

In [27]:
df.melt('반')

   반 variable  value
0  A        남     10
1  B        남     20
2  C        남     15
3  A        여     30
4  B        여     40
5  C        여     35

In [28]:
df.melt('반', var_name='성별', value_name='인원수')

   반 성별  인원수
0  A  남   10
1  B  남   20
2  C  남   15
3  A  여   30
4  B  여   40
5  C  여   35

### 11.2.4 stack 함수와 melt 함수의 언피벗 수행의 차이점
melt 함수는 인덱스를 보존하지 않아 통상은 인덱스에 필요한 데이터가 존재한다면 stack 함수를 사용함\
두 함수의 언피벗 결과는 정렬 순서가 다르지만 언피벗의 목적은 새로운 피벗 테이블 생성이기에 정렬 상태의 의미는 아주 크지 않음\
stack 함수와 melt 함수 모두 언피벗을 수행하므로 본인에게 편한 함수로 언피벗을 시도하면 됨

# 12. 데이터 그룹화하기
## 12.1 groupby 함수로 열 가공하기
### 12.1.1 groupby 함수가 필요한 이유
판다스를 배우는 목적은 원시 데이터를 능숙하게 다루려는 것임\
원시 데이터는 많은 특성을 가지기에 원시 데이터를 다루면 특성으로 그룹을 나누어 함수를 적용해야 할 일이 반드시 발생함

### 12.1.2 그룹 내에서 함수 적용하기
판다스 groupby\
그룹 내에서 함수를 적용하게 해주는 함수
```py
groupby 함수의 주요 매개변수와 인수, 기본값
df.groupby(by=None, level=None, as_index=True, sort=True, group_keys=True)
```
* by : 그룹을 나누는 기준을 지정하는데 주로 열을 지정하며 복수라면 리스트로 입력함
* level : 인덱스로 그룹을 나눌 때 기준 레벨을 지정함
* as_index : groupby 함수로 집계할 때 그룹이 인덱스가 될지 지정함
* sort : 그룹의 키로 정렬할지 지정함
* group_keys : groupby와 apply를 함께 사용할 때, 그룹의 키를 인덱스에 추가할지 지정함

In [29]:
import pandas as pd
data1 = {'반': ['A', 'B', 'A', 'B', 'B', 'A'],
         '점수': [88, 30, 78, 99, 62, 85]}
df = pd.DataFrame(data1)
df

   반  점수
0  A  88
1  B  30
2  A  78
3  B  99
4  B  62
5  A  85

오름차순으로 전체 등수를 구하기
점수 열을 인덱싱해서 rank 함수를 적용, rank 함수는 기본값으로 가장 낮은 점수에 1등을 부여하는 오름차순 방식으로 순위를 부여함

In [30]:
df['점수'].rank()

0    5.0
1    1.0
2    3.0
3    6.0
4    2.0
5    4.0
Name: 점수, dtype: float64

groupby 함수를 사용하면 전체가 아닌 반의 등수를 구할 수 있음\
df에 groupby 함수를 적용하고, 그룹의 기준이 되는 열인 '반'을 입력한 뒤, 점수 열을 인덱싱하여 rank 함수를 적용

In [31]:
df.groupby('반')['점수'].rank()

0    3.0
1    1.0
2    1.0
3    3.0
4    2.0
5    2.0
Name: 점수, dtype: float64

groupby 함수를 적용하면 그룹 나누기, 함수 적용하기, 합치기의 3가지 단계로 작업을 수행한다고 생각하면 이해하기 편함

먼저 그룹 나누기의 과정을 살펴보면 groupby 함수의 매개변수 by에 입력된 반 열을 기준으로 그룹을 나눔\
그룹의 기준을 이제부터 by로 지칭하며 함수가 적용될 대상인 점수 열이 그룹으로 나뉨\
함수가 적용되는 대상은 data로 지칭하며, 그룹으로 나뉜 data는 기존의 인덱스를 보유한 시리즈임

함수 적용하기 과정을 살펴보면 적용할 함수는 등수를 매기는 rank 함수로 그룹으로 나뉜 시리즈에 각각 rank 함수를 적용함\
그래서 B반의 점수인 30, 99, 62는 1.0, 3.0, 2.0의 등수를 받음\
rank 함수는 시리즈에 적용했을 때 시리즈를 반환하는 함수이므로 이때도 시리즈를 반환함

합치는 과정을 살펴보면 그룹으로 나누어 rank 함수를 적용했던 시리즈들은 하나의 시리즈로 합쳐지며 원본 데이터인 df의 정렬 순서대로 합침\
그래서 점수 열과 같은 인덱스 순서의 시리즈가 반환됨\
groupby 함수는 위와 같은 과정을 통해 그룹 내에서 함수를 적용함\
그래서 groupby 함수를 사용하려면 위 과정에서 필요한 세 가지를 지정해야 함
```py
df에서 반으로 그룹을 나누어 점수의 순위를 매기고 싶을 때
df.groupby('반')['점수'].rank()

1. 소괄호 안의 by는 그룹을 나누는 기준
2. 대괄호 안의 data는 함수를 적용할 열
3. rank()는 적용할 함수
```

### 12.1.3 groupby 함수로 순위 매기기
내림차순으로 반 등수 구하기

In [33]:
df.groupby('반')['점수'].rank(ascending=False)

0    1.0
1    3.0
2    3.0
3    1.0
4    2.0
5    2.0
Name: 점수, dtype: float64

df에 반등수 열로 생성하기

In [34]:
df['반등수'] = df.groupby('반')['점수'].rank(ascending=False)
df

   반  점수  반등수
0  A  88  1.0
1  B  30  3.0
2  A  78  3.0
3  B  99  1.0
4  B  62  2.0
5  A  85  2.0

### 12.1.4 groupby 함수로 행 간의 연산하기

In [35]:
import pandas as pd
# pd.options.display.max_rows = 8 # 8행까지만 출력
data = [['2025-01-03', '판다전자', 10000],
        ['2025-01-03', '성심당', 2000],
        ['2025-01-04', '성심당', 1600],
        ['2025-01-04', '판다전자', 12000],
        ['2025-01-05', '판다전자', 15000],
        ['2025-01-05', '성심당', 2000],
        ['2025-01-06', '판다전자', 13500],
        ['2025-01-06', '성심당', 2400]]

df = pd.DataFrame(data, columns=['날짜', '종목', '종가'])
df

           날짜    종목     종가
0  2025-01-03  판다전자  10000
1  2025-01-03   성심당   2000
2  2025-01-04   성심당   1600
3  2025-01-04  판다전자  12000
4  2025-01-05  판다전자  15000
5  2025-01-05   성심당   2000
6  2025-01-06  판다전자  13500
7  2025-01-06   성심당   2400

df에 전일 종가를 새로운 열로 만들고자 하면 shift 함수를 이용하여 시리즈를 지정한만큼 밀 수 있음\
단일 종목만 있었다면 전일 종가 데이터를 쉽게 열로 만들었을 것이지만 df는 판다전자와 성심당의 데이터가 섞여 있음\
따라서 각 종목의 전일 종가 데이터를 생성하고자 그룹화 작업이 필요한데 종목으로 그룹을 나누어 종가 열에 shift 함수를 적용하기에, by는 종목, data는 종가, 적용할 함수는 shift

In [36]:
df['전일종가'] = df.groupby('종목')['종가'].shift()
df

           날짜    종목     종가     전일종가
0  2025-01-03  판다전자  10000      NaN
1  2025-01-03   성심당   2000      NaN
2  2025-01-04   성심당   1600   2000.0
3  2025-01-04  판다전자  12000  10000.0
4  2025-01-05  판다전자  15000  12000.0
5  2025-01-05   성심당   2000   1600.0
6  2025-01-06  판다전자  13500  15000.0
7  2025-01-06   성심당   2400   2000.0

shift와 비슷한 함수 diff와 pct_change 함수도 groupby와 사용하는데 이번에는 전일 대비 등락 열과 등락률 열을 생성

In [37]:
df['등락'] = df.groupby('종목')['종가'].diff()
df

           날짜    종목     종가     전일종가      등락
0  2025-01-03  판다전자  10000      NaN     NaN
1  2025-01-03   성심당   2000      NaN     NaN
2  2025-01-04   성심당   1600   2000.0  -400.0
3  2025-01-04  판다전자  12000  10000.0  2000.0
4  2025-01-05  판다전자  15000  12000.0  3000.0
5  2025-01-05   성심당   2000   1600.0   400.0
6  2025-01-06  판다전자  13500  15000.0 -1500.0
7  2025-01-06   성심당   2400   2000.0   400.0

In [38]:
df['등락률'] = df.groupby('종목')['종가'].pct_change()
df

           날짜    종목     종가     전일종가      등락   등락률
0  2025-01-03  판다전자  10000      NaN     NaN   NaN
1  2025-01-03   성심당   2000      NaN     NaN   NaN
2  2025-01-04   성심당   1600   2000.0  -400.0 -0.20
3  2025-01-04  판다전자  12000  10000.0  2000.0  0.20
4  2025-01-05  판다전자  15000  12000.0  3000.0  0.25
5  2025-01-05   성심당   2000   1600.0   400.0  0.25
6  2025-01-06  판다전자  13500  15000.0 -1500.0 -0.10
7  2025-01-06   성심당   2400   2000.0   400.0  0.20

### 12.1.5 groupby 함수로 전후방 값으로 결측값 대체하기

In [39]:
import pandas as pd
data1 = [['2025-01-03', '판다전자', 10000, float('nan')],
         ['2025-01-03', '성심당', 2000, float('nan')],
         ['2025-01-04', '성심당', 1600, 1],
         ['2025-01-04', '판다전자', 12000, float('nan')],
         ['2025-01-05', '판다전자', 15000, 2],
         ['2025-01-05', '성심당', 2000, float('nan')],
         ['2025-01-06', '판다전자', 13500, float('nan')],
         ['2025-01-06', '성심당', 2400, float('nan')]]

df1 = pd.DataFrame(data1, columns=['날짜', '종목', '종가', '구매'])
df1

           날짜    종목     종가   구매
0  2025-01-03  판다전자  10000  NaN
1  2025-01-03   성심당   2000  NaN
2  2025-01-04   성심당   1600  1.0
3  2025-01-04  판다전자  12000  NaN
4  2025-01-05  판다전자  15000  2.0
5  2025-01-05   성심당   2000  NaN
6  2025-01-06  판다전자  13500  NaN
7  2025-01-06   성심당   2400  NaN

In [40]:
df1['보유']=df1.groupby('종목')['구매'].ffill()
df1

           날짜    종목     종가   구매   보유
0  2025-01-03  판다전자  10000  NaN  NaN
1  2025-01-03   성심당   2000  NaN  NaN
2  2025-01-04   성심당   1600  1.0  1.0
3  2025-01-04  판다전자  12000  NaN  NaN
4  2025-01-05  판다전자  15000  2.0  2.0
5  2025-01-05   성심당   2000  NaN  1.0
6  2025-01-06  판다전자  13500  NaN  2.0
7  2025-01-06   성심당   2400  NaN  1.0

In [41]:
# 보유 이후의 주가 데이터만 필터링
df1[df1['보유'].notna()]

           날짜    종목     종가   구매   보유
2  2025-01-04   성심당   1600  1.0  1.0
4  2025-01-05  판다전자  15000  2.0  2.0
5  2025-01-05   성심당   2000  NaN  1.0
6  2025-01-06  판다전자  13500  NaN  2.0
7  2025-01-06   성심당   2400  NaN  1.0

In [42]:
# 첫 번째 구매 종목의 구매 이후 주가 추이
df1[df1['보유'].eq(1)]

           날짜   종목    종가   구매   보유
2  2025-01-04  성심당  1600  1.0  1.0
5  2025-01-05  성심당  2000  NaN  1.0
7  2025-01-06  성심당  2400  NaN  1.0

### 12.1.6 groupby 함수로 누적 합 구하기
누적 합을 구하는 cumsum 함수도 groupby 함수와 함께 자주 활용됨

In [43]:
import pandas as pd
data = [['2021-01-01', '김판다', 10000], ['2021-01-01', '강승주', 2000],
        ['2021-01-02', '김판다', 20000], ['2021-01-02', '강승주', 5000],
        ['2021-01-03', '강승주', 8000], ['2021-01-03', '김판다', 5000]]
df = pd.DataFrame(data, columns=['날짜', '이름', '입금액'])
df

           날짜   이름    입금액
0  2021-01-01  김판다  10000
1  2021-01-01  강승주   2000
2  2021-01-02  김판다  20000
3  2021-01-02  강승주   5000
4  2021-01-03  강승주   8000
5  2021-01-03  김판다   5000

df는 각 인원의 날짜별 입금액이 나타나는 데이터 프레임인데 각 인원의 누적 입금액을 구하려면 이름 열로 그룹을 나누어 입금액에 cumsum 함수를 적용하기에 by는 이름이고 data는 입금액, 적용할 함수는 cumsum

In [44]:
df['누적입금'] = df.groupby('이름')['입금액'].cumsum()
df

           날짜   이름    입금액   누적입금
0  2021-01-01  김판다  10000  10000
1  2021-01-01  강승주   2000   2000
2  2021-01-02  김판다  20000  30000
3  2021-01-02  강승주   5000   7000
4  2021-01-03  강승주   8000  15000
5  2021-01-03  김판다   5000  35000

cumsum 함수는 불 자료형의 특성과 결합해 그룹의 기준도 만들 수 있음

In [45]:
data1 = [['07:35', 'A', 'Log_in', float('nan')],
         ['07:36', 'A', 'Buy', 2000.0],
         ['07:37', 'A', 'Log_out', float('nan')],
         ['10:30', 'B', 'Log_in', float('nan')],
         ['11:20', 'B', 'Buy', 4000.0],
         ['11:32', 'A', 'Log_in', float('nan')],
         ['11:34', 'B', 'Buy', 3000],
         ['11:35', 'B', 'Log_out', float('nan')],
         ['11:36', 'A', 'Buy', 5000.0],
         ['11:37', 'A', 'Log_out', float('nan')]]
df1 = pd.DataFrame(data1, columns=['시간', '회원코드', '로그', '구매금액'])
df1

      시간 회원코드       로그    구매금액
0  07:35    A   Log_in     NaN
1  07:36    A      Buy  2000.0
2  07:37    A  Log_out     NaN
3  10:30    B   Log_in     NaN
4  11:20    B      Buy  4000.0
5  11:32    A   Log_in     NaN
6  11:34    B      Buy  3000.0
7  11:35    B  Log_out     NaN
8  11:36    A      Buy  5000.0
9  11:37    A  Log_out     NaN

df1은 쇼핑몰의 로그 데이터이며 시간에 따라 각 회원의 로그 기록을 나타내는데 이 데이터를 각 회원의 로그인을 기준으로 추가로 그룹 나눔

In [46]:
df1['로그인'] = df1['로그']=='Log_in'
df1

      시간 회원코드       로그    구매금액    로그인
0  07:35    A   Log_in     NaN   True
1  07:36    A      Buy  2000.0  False
2  07:37    A  Log_out     NaN  False
3  10:30    B   Log_in     NaN   True
4  11:20    B      Buy  4000.0  False
5  11:32    A   Log_in     NaN   True
6  11:34    B      Buy  3000.0  False
7  11:35    B  Log_out     NaN  False
8  11:36    A      Buy  5000.0  False
9  11:37    A  Log_out     NaN  False

생성된 로그인 열은 True와 False로 이루어지므로 회원코드로 그룹을 나누어 누적 합을 구하면 각 회원의 활동을 로그인 기준으로 다시 그룹이 나뉨\
by는 회원코드, data는 로그인, 적용할 함수는 cumsum

In [47]:
df1['그룹'] = df1.groupby('회원코드')['로그인'].cumsum()
df1

      시간 회원코드       로그    구매금액    로그인  그룹
0  07:35    A   Log_in     NaN   True   1
1  07:36    A      Buy  2000.0  False   1
2  07:37    A  Log_out     NaN  False   1
3  10:30    B   Log_in     NaN   True   1
4  11:20    B      Buy  4000.0  False   1
5  11:32    A   Log_in     NaN   True   2
6  11:34    B      Buy  3000.0  False   1
7  11:35    B  Log_out     NaN  False   1
8  11:36    A      Buy  5000.0  False   2
9  11:37    A  Log_out     NaN  False   2

이렇게 기존의 열을 가공해 그룹을 나누는 기준을 생성한 것을 그루퍼라고 함\
빅데이터를 다루면 그루퍼를 생성해야 할 일이 빈번하므로 cumsum 함수와 groupby 함수를 조합해 생성하는 것을 알아두면 좋음\
회원 코드열과 그룹 열로 나누어 구매 금액의 합을 집계하는 방법

In [49]:
df1.pivot_table('구매금액',index='회원코드',columns='그룹', aggfunc='sum')

그룹         1       2
회원코드
A     2000.0  5000.0
B     7000.0     NaN

### 12.1.7 groupby 함수로 순번 구하기
판다스 cumcount\
그룹으로 나누어 순번을 매기는 함수이며 반드시 그룹화를 수행하는 함수와 함께 사용함
```py
cumcount 함수의 주요 매개변수와 인수, 기본값
DataFrameGroupBy.cumcount(ascending=True)
```
* ascending : 오름차순 혹은 내림차순으로 순번을 부여할 것을 지정하는데 기본값은 True이며 오름차순

판다스 cumcount 함수는 등장에 따라 순번을 매기는 함수로 반드시 그룹을 나누는 함수와 함께 사용해야 함

In [50]:
import pandas as pd
data = {'제품': ['A', 'B', 'B', 'A', 'C', 'A'],
        '판매량': [10, 20, 30, 40, 50, 60]}
df = pd.DataFrame(data)
df

  제품  판매량
0  A   10
1  B   20
2  B   30
3  A   40
4  C   50
5  A   60

제품으로 그룹을 나누어 순번을 매겨볼 것인데 groupby 함수를 적용하며 by는 제품을 지정하고 적용할 함수로 cumcount를 지정함\
cumcount 함수는 특정 열에 적용하는 함수가 아니라서 별도의 인덱싱 없이 바로 사용할 수 있음

In [51]:
df['순번'] = df.groupby('제품').cumcount()
df

  제품  판매량  순번
0  A   10   0
1  B   20   0
2  B   30   1
3  A   40   1
4  C   50   0
5  A   60   2

In [52]:
# 제품과 순번으로 그룹을 나누어 판매량을 피벗하기
df.pivot(index='제품',columns='순번',values='판매량')

순번     0     1     2
제품
A   10.0  40.0  60.0
B   20.0  30.0   NaN
C   50.0   NaN   NaN

In [55]:
# 그룹을 나누지 않을 때 전체의 순번을 매기는 방법
import numpy as np
df['전체순번'] = range(0, len(df)) # 기본 파이썬의 방법
df['전체순번'] = np.arange(0, len(df)) # 넘파이의 방법
df['전체순번'] = pd.RangeIndex(0, len(df)) # 판다스의 방법
df

  제품  판매량  순번  전체순번
0  A   10   0     0
1  B   20   0     1
2  B   30   1     2
3  A   40   1     3
4  C   50   0     4
5  A   60   2     5

### 12.1.8 집계 결과를 열로 생성하기(transform)
판다스 transform\
주로 groupby 함수와 사용해 집계 결과로 시리즈를 생성하는 함수이며 groupby 함수에 사용자 정의 함수를 적용해 열을 생성할 때도 쓰임

groupby 함수와 transform 함수를 조합하면 집계 결과를 시리즈로 생성할 수 있음\
생성된 시리즈는 기존 데이터 프레임의 열로 만들 수 있으며, 꽤 유용한 특성임

In [56]:
import pandas as pd
data = {'제품': ['A', 'A', 'B', 'B', 'C', 'A'],
        '판매량': [10, 20, 20, 30, 10, 60]}
df = pd.DataFrame(data)
df

  제품  판매량
0  A   10
1  A   20
2  B   20
3  B   30
4  C   10
5  A   60

df는 각 제품의 판매량을 나타내는 데이터로 각 제품의 전체 판매량을 별도의 열로 추가하려 함\
제품으로 그룹을 나누어 판매량 열에 transform 함수를 적용하고 transform 함수에 인수 'sum'을 입력하면 집계 결과를 시리즈로 반환

In [57]:
df.groupby('제품')['판매량'].transform('sum')

0    90
1    90
2    50
3    50
4    10
5    90
Name: 판매량, dtype: int64

In [58]:
df['제품총판매'] = df.groupby('제품')['판매량'].transform('sum')
df

  제품  판매량  제품총판매
0  A   10     90
1  A   20     90
2  B   20     50
3  B   30     50
4  C   10     10
5  A   60     90

In [59]:
df['비중'] = df['판매량'] / df['제품총판매']
df

  제품  판매량  제품총판매        비중
0  A   10     90  0.111111
1  A   20     90  0.222222
2  B   20     50  0.400000
3  B   30     50  0.600000
4  C   10     10  1.000000
5  A   60     90  0.666667

In [60]:
# 2행 이상의 제품 데이터만 필터링
cond = df.groupby('제품')['판매량'].transform('count')>=2
df[cond]

  제품  판매량  제품총판매        비중
0  A   10     90  0.111111
1  A   20     90  0.222222
2  B   20     50  0.400000
3  B   30     50  0.600000
5  A   60     90  0.666667

### 12.1.9 transform 함수로 사용자 저으이 함수 적용하기
transform 함수의 인수로 사용자 정의 함수도 입력할 수 있음\
그룹마다 최댓값과 최솟값의 차이를 구해 열로 만들자

In [61]:
x = pd.Series([1, 2, 4, 5])
x.max() - x.min()

np.int64(4)

In [62]:
df.groupby('제품')['판매량'].transform(lambda x : x.max() - x.min())

0    50
1    50
2    10
3    10
4     0
5    50
Name: 판매량, dtype: int64

열 가공 함수이지만 메서드로 활용할 수 없다면 transform 함수가 좋은 방법임\
대부분의 열 가공 함수가 메서드로 활용할 수 있으나, cut 함수나 qcut 함수처럼 메서드로 활용할 수 없는 함수들이 일부 존재함\
또한 사용자 정의 함수는 태생적으로 메서드로 활용할 수 없으니 transform 함수가 필요함

In [63]:
data1 = {'상품종류': ['스낵', '스낵', '스낵', '핸드폰', '핸드폰', '핸드폰'],
        '상품코드': ['S001', 'S002', 'S003', 'P001', 'P002', 'P003'],
        '가격': [6000, 10000, 4000, 10000, 1000000, 500000]}
df1 = pd.DataFrame(data1)
df1

  상품종류  상품코드       가격
0   스낵  S001     6000
1   스낵  S002    10000
2   스낵  S003     4000
3  핸드폰  P001    10000
4  핸드폰  P002  1000000
5  핸드폰  P003   500000

df1은 각 상품의 카테고리 분류와 가격에 대한 데이터인데 각 상품을 가격에 따라 저가, 중가, 고가로 균등 분할해 또 다른 범주화를 수행\
전체를 1/3로 나누어 저가, 중가, 고가로 분류하되 같은 상품 종류 내에서 분류할 때 qcut 함수를 활용하면 손쉽게 범주화가 가능함\
하지만 qcut 함수는 반드시 pd.qcut인 함수 형태로 사용해야 하기에 transform 함수가 필요하며 lambda를 사용하면 편리함

In [66]:
df1['분류'] = df1.groupby('상품종류')['가격'].transform(
    lambda x : pd.qcut(x, q=3, labels=['저가','중가','고가'])
)
df1

  상품종류  상품코드       가격  분류
0   스낵  S001     6000  중가
1   스낵  S002    10000  고가
2   스낵  S003     4000  저가
3  핸드폰  P001    10000  저가
4  핸드폰  P002  1000000  고가
5  핸드폰  P003   500000  중가

In [67]:
# lambda를 사용하지 않고 진행하는 방법
df1['분류'] = df1.groupby('상품종류')['가격'].transform(
    pd.qcut, q=3, labels=['저가','중가','고가']
)
df1

  상품종류  상품코드       가격  분류
0   스낵  S001     6000  중가
1   스낵  S002    10000  고가
2   스낵  S003     4000  저가
3  핸드폰  P001    10000  저가
4  핸드폰  P002  1000000  고가
5  핸드폰  P003   500000  중가

## 12.2 groupby 함수로 집계하기
이제까지 groupby 함수와 사용했던 함수들은 rank 함수처럼 시리즈에 적용하면 시리즈를 반환하는 열 가공 함수였음\
groupby 함수와 집계 함수를 적용하면 pivot_table 함수를 적용했을 때처럼 그룹으로 나누어 집계할 수 있음

### 12.2.1 groupby 함수로 집계 함수 적용하기

In [70]:
import pandas as pd
# pd.options.display.float_format = '{:.2f}'.format # 소수점 둘째 자리 출력
data1 = {'반': ['A', 'B', 'A', 'B', 'B', 'A'],
         '점수': [88, 30, 78, 99, 62, 85]}
df = pd.DataFrame(data1)
df

   반  점수
0  A  88
1  B  30
2  A  78
3  B  99
4  B  62
5  A  85

반으로 그룹을 나누고 점수 열의 평균을 구하려면 groupby 함수에 그룹을 나누는 기준으로 반을 입력하고 점수 열을 인덱싱한 다음 집계 함수인 mean을 적용함

In [71]:
df.groupby('반')['점수'].mean()

반
A    83.666667
B    63.666667
Name: 점수, dtype: float64

### 12.2.2 groupby 함수로 집계하기와 피벗 테이블의 차이
groupby 함수를 사용하면 그룹 집계를 수행할 수 있으며 pivot_table 함수 역시 그룹 집계를 수행함\
그렇다면 groupby 함수의 그룹 집계와 피벗 테이블은 어떤 차이가 존재하는가?\
결론적으로 두 방식은 결과의 구조만 다를 뿐 비슷한 기능을 수행함

In [72]:
import pandas as pd
# pd.options.display.float_format = '{:.2f}'.format # 소수점 둘째 자리 출력
data1 = [['김판다', 'A', '남', 95, 90], ['최진환', 'B', '남', 93, 90],
         ['조민영', 'B', '여', 88, 80], ['박연준', 'A', '남', 85, 70],
         ['강승주', 'B', '여', 78, 90], ['안지선', 'A', '여', 72, 70]]
df1 = pd.DataFrame(data1, columns=['이름', '반', '성별', '국어', '영어'])
df1

    이름  반 성별  국어  영어
0  김판다  A  남  95  90
1  최진환  B  남  93  90
2  조민영  B  여  88  80
3  박연준  A  남  85  70
4  강승주  B  여  78  90
5  안지선  A  여  72  70

In [73]:
df1.groupby(['반', '성별'])['국어'].mean()

반  성별
A  남     90.0
   여     72.0
B  남     93.0
   여     83.0
Name: 국어, dtype: float64

In [74]:
df1.pivot_table('국어', index='반', columns='성별', aggfunc='mean')

성별     남     여
반
A   90.0  72.0
B   93.0  83.0

In [75]:
df1.groupby(['반', '성별'])['국어'].mean().unstack()

성별     남     여
반
A   90.0  72.0
B   93.0  83.0

In [76]:
df1.pivot_table('국어', index=['반', '성별'], aggfunc='mean')

        국어
반 성별
A 남   90.0
  여   72.0
B 남   93.0
  여   83.0

동일한 집계 결과를 반환할 수 있지만 간단한 교차표를 만들 때는 pivot_table 함수가 더 편리함\
복잡한 구조의 피벗 테이블은 오히려 groupby 함수가 뛰어난데, 예를 들어 복수의 열을 집계할 때는 groupby 함수가 더 편리함\
groupby 함수로 복수의 열을 한 번에 집계할 때는 복수의 열을 리스트로 묶어 대괄호에 입력함(pivot_table 함수로도 복수의 열을 집계하는 것이 가능하지만 groupby 쪽이 더 편리함)

In [77]:
df1.groupby(['반', '성별'])[['국어','영어']].mean()

        국어    영어
반 성별
A 남   90.0  80.0
  여   72.0  70.0
B 남   93.0  90.0
  여   83.0  85.0

### 12.2.3 groupby 함수와 agg 함수로 집계하기
groupby 함수는 agg 함수와 조합해 맞춤형 피벗 테이블 생성이 용이하며 agg 함수는 맞춤형 집계에 큰 강점을 가짐\
agg 함수는 aggregate의 약자로 집계 함수를 적용하는 것에 특화된 함수이며 여러 가지 간편한 부가 기능을 제공함\
여러 집계 함수를 동시에 적용할 수 있고 열마다 다른 집계 함수를 사용할 수 있음

agg 함수의 장점
1. 여러 집계 함수를 동시에 적용할 수 있음\
$\rightarrow$ 복수의 집계 함수를 리스트로 묶어 인수로 입력
2. 열마다 다른 집계 함수를 사용할 수 있음\
$\rightarrow$ 적용할 열과 집계 함수를 딕셔너리의 키와 밸류로 묶어 인수로 입력
3. 열마다 다른 집계 함수를 사용하고, 집계된 열 이름을 지정할 수 있음\
$\rightarrow$ 열 이름을 매개변수로 입력하고, 집계 함수를 적용할 열과 함수를 튜플로 묶어 인수로 입력

In [78]:
df1

    이름  반 성별  국어  영어
0  김판다  A  남  95  90
1  최진환  B  남  93  90
2  조민영  B  여  88  80
3  박연준  A  남  85  70
4  강승주  B  여  78  90
5  안지선  A  여  72  70

df1에서 반과 성별을 기준으로 그룹을 나누어 국어의 최고 점수와 최저 점수를 동시에 구하자\
반과 성별을 리스트로 묶어 by에 입력하고, 국어 열을 대괄호로 인덱싱한 후 agg 함수를 적용\
agg 함수의 인수로 최댓값을 구하는 'max'와 최솟값을 구하는 'min'을 리스트로 묶어 입력함

In [79]:
df1.groupby(['반','성별'])['국어'].agg(['max','min'])

      max  min
반 성별
A 남    95   85
  여    72   72
B 남    93   93
  여    88   78

열마다 다른 집계 함수도 적용해 보자\
영어 열은 평균을 집계하고, 국어 열은 인원수를 집계하자\
적용할 열과 집계 함수를 딕셔너리의 키와 밸류로 묶어 agg 함수의 인수로 입력하며, agg 함수에서 함수를 적용할 열과 함수를 개별적으로 지정하므로 대괄호 인덱싱은 생략함

In [80]:
df1.groupby(['반', '성별']).agg({'영어' : 'mean', '국어' : 'count'})

        영어  국어
반 성별
A 남   80.0   2
  여   70.0   1
B 남   90.0   1
  여   85.0   2

위 예제의 결과를 보면 집계 결과의 열 이름은 집계 대상 열과 동일한데 집계 결과의 열 이름을 수정해야 할 때도 존재함
```py
df1.groupby().agg(새로운_열_이름 = ('대상열_이름', 함수))
```
위와 같은 형태로 사용함

In [81]:
df1.groupby(['반', '성별']).agg(
    영어평균 = ('영어', 'mean'),
    국어평균 = ('국어', 'mean'),
    인원수 = ('국어', 'count')
)

      영어평균  국어평균  인원수
반 성별
A 남   80.0  90.0    2
  여   70.0  72.0    1
B 남   90.0  93.0    1
  여   85.0  83.0    2

### 12.2.4 문자열의 결합
파이썬에는 문자열을 결합하는 join 함수가 있는데, 구분자를 지정하고 결합 대상인 배열을 입력하면 배열의 문자열을 구분자로 구분해 하나로 결합해주는 함수로, 리스트뿐 아니라 시리즈에도 사용함

In [82]:
s = pd.Series(['A', 'BC', 'DEF'])
'/'.join(s)

'A/BC/DEF'

시리즈에 적용 가능한 함수이지만 단독으로 groupby 함수에 적용할 수는 없음\
groupby 함수와 조합하는 함수는 메서드 형태여야 하는데, join 함수는 판다스 함수가 아니므로 시리즈에 메서드로 적용할 수 없음\
이처럼 메서드로 사용할 수 없는 집계 함수는 agg 함수와 조합해 사용함

In [83]:
df1

    이름  반 성별  국어  영어
0  김판다  A  남  95  90
1  최진환  B  남  93  90
2  조민영  B  여  88  80
3  박연준  A  남  85  70
4  강승주  B  여  78  90
5  안지선  A  여  72  70

In [84]:
df1.groupby('영어').agg(학생=('이름', '/'.join))

             학생
영어
70      박연준/안지선
80          조민영
90  김판다/최진환/강승주

### 12.2.5 agg 함수로 사용자 정의 함수 적용하기
사용자 정의 함수 역시 메서드 형태로 사용할 수 없기에 agg 함수에 입력해야 함\
이때 적용할 사용자 정의 함수는 반드시 차원이 축소되는 집계 함수여야 함\
생성한 사용자 정의 함수가 집계 함수가 아니라면 transform 함수를 사용함\
국어 열의 최대와 최소의 격차를 lambda 함수로 집계할 것인데 최대와 최소의 격차는 차원이 축소되는 집계 함수이기에 agg 함수로 적용

In [85]:
df1.groupby('반').agg(
    최대_최소=('국어', lambda x: x.max() - x.min())
)

   최대_최소
반
A     23
B     15

최대, 최소를 구하여 뺄셈을 해도 격차를 구할 수 있지만, lambda 함수를 사용해 한번에 집계한다면 agg 함수에 lambda 함수를 입력함\
조건에 맞는 대상만 집계할 때도 lambda 함수가 유용한데 where 함수를 사용하면 조건에 맞지 않는 대상을 NaN으로 변환함\\
mean처럼 판다스의 집계 함수는 NaN을 제외하고 집계를 수행하기에 where 함수와 mean 함수를 조합하면 조건에 맞는 대상의 평균만을 구함

In [86]:
cond = df1['성별'] == '남'
df1['국어'].where(cond).mean()

np.float64(91.0)

In [87]:
cond = df1['성별'] == '남'
df1.groupby('반').agg(
    국어_남자_평균=('국어', lambda x: x.where(cond).mean()),
    국어_여자_평균=('국어', lambda x: x.where(~cond).mean()),
    국어_전체_평균=('국어', 'mean')
)

   국어_남자_평균  국어_여자_평균   국어_전체_평균
반
A      90.0      72.0  84.000000
B      93.0      83.0  86.333333

### 12.2.6 agg 함수와 transform 함수의 차이
지금까지 함수를 적용하는 함수인 agg 함수와 transform 함수를 학습하였는데 두 함수의 차이점은 다음과 같음
* agg 함수 : 집계할 때 사용하며, 집계 함수만 입력이 가능하고, 집계 결과를 반환함
* transform 함수 : 열을 생성할 때 사용하며 열을 만들 수 있는 시리즈를 반환함\
시리즈를 생성하는 다양한 함수를 입력할 수 있으며, 집계 함수를 입력해도 시리즈를 반환함

In [89]:
df

   반  점수
0  A  88
1  B  30
2  A  78
3  B  99
4  B  62
5  A  85

In [90]:
df.groupby('반')['점수'].agg('mean')

반
A    83.666667
B    63.666667
Name: 점수, dtype: float64

In [91]:
df.groupby('반')['점수'].transform('mean')

0    83.666667
1    63.666667
2    83.666667
3    63.666667
4    63.666667
5    83.666667
Name: 점수, dtype: float64

## 12.3 groupby 심화
### 12.3.1 groupby 함수의 여러 가지 매개변수

In [92]:
import pandas as pd
data1 = [[1, 'A', '반장', '물리001', 94],
         [1, 'A', '부반장', '화학001', 90],
         [2, 'A', '부반장', '화학002', 85],
         [2, 'A', '반원', '물리002', 95],
         [1, 'B', '부반장', '물리003', 86],
         [1, 'B', '반장', '화학003', 75],
         [1, 'B', '반원', '화학004', 80]]
df = pd.DataFrame(data1, columns=['학년', '반', '직책', '학생코드', '점수'])
df1 = df.set_index(['학년', '반']).copy()
df

   학년  반   직책   학생코드  점수
0   1  A   반장  물리001  94
1   1  A  부반장  화학001  90
2   2  A  부반장  화학002  85
3   2  A   반원  물리002  95
4   1  B  부반장  물리003  86
5   1  B   반장  화학003  75
6   1  B   반원  화학004  80

df는 학생마다 학년, 반, 반에서의 직책, 점수가 나타나고, 학생코드 열에는 선택 과목이 표현된 코드가 입력됨\
df1은 df와 유사한 데이터이지만, 학년과 반의 데이터가 인덱스에 위치함

as_index는 집계 후 그룹을 인덱스에 위치시킬지, 일반 열로 만들지를 결정하는 매개변수\
기본값은 True라 이제까지의 집계 결과는 각 그룹이 인덱스에 위치하였지만 False를 입력하면 일반 열로 생성됨

In [93]:
# groupby 함수의 매개변수 as_index 활용
df.groupby(['학년', '반'], as_index=False)['점수'].mean()

   학년  반         점수
0   1  A  92.000000
1   1  B  80.333333
2   2  A  90.000000

각 그룹이 인덱스가 아닌 일반 열이 되므로 집계 결과도 시리즈가 아니라 데이터 프레임으로 반환됨\
as_index=False를 사용하지 않고 집계 결과에 추가로 reset_index 함수를 적용해도 동일한 결과를 얻음

df의 데이터는 2학년 A반이 1학년 B반보다 먼저 등장하지만 위의 결과를 보면 1학년 B반이 2학년 A반보다 우선함\
그룹의 정렬을 수행한 후 집계하기 때문인데 sort=False를 입력하면 정렬을 수행하지 않음

In [94]:
df.groupby(['학년','반'], sort=False)['점수'].mean()

학년  반
1   A    92.000000
2   A    90.000000
1   B    80.333333
Name: 점수, dtype: float64

df1처럼 그룹의 기준이 인덱스에 위치한다면 by 대신 level로 그룹을 나누는 기준을 지정함

In [95]:
df1

       직책   학생코드  점수
학년 반
1  A   반장  물리001  94
   A  부반장  화학001  90
2  A  부반장  화학002  85
   A   반원  물리002  95
1  B  부반장  물리003  86
   B   반장  화학003  75
   B   반원  화학004  80

In [96]:
df1.groupby(level=[0,1])['점수'].mean()

학년  반
1   A    92.000000
    B    80.333333
2   A    90.000000
Name: 점수, dtype: float64

### 12.3.2 그룹바이 객체
데이터 프레임에 groupby 함수를 적용한 결과가 그룹바이 객체

In [97]:
df.groupby(['학년','반'])

그룹바이 객체는 객체의 클래스와 메모리 주소를 나타내는 형식으로 출력됨\
list 함수를 그룹바이 객체에 적용해 확인해보자

In [98]:
list(df.groupby(['학년','반']))

[((np.int64(1), 'A'),
     학년  반   직책   학생코드  점수
  0   1  A   반장  물리001  94
  1   1  A  부반장  화학001  90),
 ((np.int64(1), 'B'),
     학년  반   직책   학생코드  점수
  4   1  B  부반장  물리003  86
  5   1  B   반장  화학003  75
  6   1  B   반원  화학004  80),
 ((np.int64(2), 'A'),
     학년  반   직책   학생코드  점수
  2   2  A  부반장  화학002  85
  3   2  A   반원  물리002  95)]

그룹바이 객체는 그룹의 키와 해당 그룹에 속하는 데이터 프레임이 튜플로 묶인 구조이기에 다음과 같이 그룹으로 분할된 데이터 프레임을 리스트에 담을 수 있음

In [99]:
dfs = [i for key, i in df.groupby(['학년','반'])]
dfs

[   학년  반   직책   학생코드  점수
 0   1  A   반장  물리001  94
 1   1  A  부반장  화학001  90,
    학년  반   직책   학생코드  점수
 4   1  B  부반장  물리003  86
 5   1  B   반장  화학003  75
 6   1  B   반원  화학004  80,
    학년  반   직책   학생코드  점수
 2   2  A  부반장  화학002  85
 3   2  A   반원  물리002  95]

그룹바이 객체도 변수로 지정할 수 있으며 동일한 그룹바이 객체를 반복해서 사용한다면 변수로 지정하는 것이 훨씬 편리함\
학년과 반으로 나누어 점수의 평균을 구한 뒤 그룹 내 표준편차를 더하자\
반복해서 그룹바이 객체를 사용할 것이니 변수 g로 지정하자

In [100]:
g = df.groupby(['학년','반'])
g['점수'].mean() + g['점수'].std()

학년  반
1   A    94.828427
    B    85.840904
2   A    97.071068
Name: 점수, dtype: float64

### 12.3.3 groupby 함수와 head, tail, sample
데이터의 순서에 따라 일부만 가져오게 하는 head, tail 함수도 groupby 함수와 조합함

In [101]:
g.head(1)

   학년  반   직책   학생코드  점수
0   1  A   반장  물리001  94
2   2  A  부반장  화학002  85
4   1  B  부반장  물리003  86

무작위로 추출하는 sample 함수도 groupby 함수와 조합됨\
그룹마다 1행씩 추출하며 이때 random_state로 시드를 부여해 고정된 무작위 추출을 수행

In [102]:
g.sample(1, random_state=0)

   학년  반   직책   학생코드  점수
1   1  A  부반장  화학001  90
6   1  B   반원  화학004  80
2   2  A  부반장  화학002  85

### 12.3.4 그루퍼
groupby 함수는 열뿐만 아니라 인덱스를 기준으로도 그룹을 나누고, 입력한 배열을 기준으로도 그룹을 나눔\
그룹의 기준을 데이터 프레임 내부에서 지정하는 것이 아니라 외부의 배열로 지정할 때, 그룹의 기준이 되는 배열을 그루퍼라고 함\
df의 학생코드 열은 각 학생의 선택 과목을 나타냄\
선택 과목을 기준으로 집계를 수행하자\
학생 코드 열에서 선택 과목의 데이터를 추출해 별도의 열을 생성하면 groupby 함수가 적용됨\
이때 별도의 열을 생성하지 않고 가장 위 행부터 차례로 그룹을 지정해 리스트로 입력해도 그룹을 나눌 수 있음

In [104]:
df

   학년  반   직책   학생코드  점수
0   1  A   반장  물리001  94
1   1  A  부반장  화학001  90
2   2  A  부반장  화학002  85
3   2  A   반원  물리002  95
4   1  B  부반장  물리003  86
5   1  B   반장  화학003  75
6   1  B   반원  화학004  80

In [105]:
grp1 = ['물리', '화학', '화학', '물리', '물리', '화학', '화학']
df.groupby(grp1)['점수'].mean()

물리    91.666667
화학    82.500000
Name: 점수, dtype: float64

변수 grp1이 그룹을 나누는 기준이 되는 배열이고 이를 그루퍼라고 지칭함\
다만 리스트로 직접 생성하는 방식은 지나치게 번거로운데 7행 정도라면 가능하지만 빅데이터에서는 불가능함\
주로 원본 데이터를 처리한 결과를 그루퍼로 활용함

df1의 학생코드 열에서 각 셀의 앞 두글자만 인덱싱하면 과목의 데이터가 되는데 이 시리즈를 그루퍼로 사용

In [106]:
grp2 = df['학생코드'].str[:2]
df.groupby(grp2)['점수'].mean()

학생코드
물리    91.666667
화학    82.500000
Name: 점수, dtype: float64

그루퍼를 활용하면 별도의 열을 생성하지 않고 기존 데이터를 가공하는 것만으로 그룹 집계가 가능함\
그루퍼는 원본 데이터를 변환하지 않는 장점이 있으며, 특히 열이 없는 시리즈에 groupby 함수를 적용할 때는 대부분 그루퍼를 사용함

### 12.3.5 transform 함수를 활용한 다양한 그룹 필터링(all, any)
groupby 함수와 transform 함수를 활용하여 그룹 필터링을 수행할 때 특정 데이터의 존재 여부로 그룹을 필터링해볼 것임

df를 복제한 df2에서 반장이 존재하는 데이터만 추출하고, 반장 여부를 True, False로 반환하는 반장 열을 생성\
그리고 학년과 반으로 그룹을 나누어 반장 열에 transform 함수를 적용함\
transform 함수에 집계 함수 any를 입력하면 True가 존재하는 그룹에만 True인 시리즈를 싱성하기에 반장이 존재하는 반을 필터링함

In [107]:
df2 = df.copy()
df2

   학년  반   직책   학생코드  점수
0   1  A   반장  물리001  94
1   1  A  부반장  화학001  90
2   2  A  부반장  화학002  85
3   2  A   반원  물리002  95
4   1  B  부반장  물리003  86
5   1  B   반장  화학003  75
6   1  B   반원  화학004  80

In [108]:
df2['반장'] = df2['직책'].eq('반장')
cond1 = df2.groupby(['학년', '반'])['반장'].transform('any')
df2[cond1]

   학년  반   직책   학생코드  점수     반장
0   1  A   반장  물리001  94   True
1   1  A  부반장  화학001  90  False
4   1  B  부반장  물리003  86  False
5   1  B   반장  화학003  75   True
6   1  B   반원  화학004  80  False

any 함수와 all 함수를 transform 함수와 조합해 특정 데이터를 보유한 그룹 전체를 필터링하는 것은 유용한 기법\
그루퍼를 사용하면 별도의 열을 생성하지 않고도 깔끔하게 같은 작업을 수행함

In [109]:
cond2 = df['직책'].eq('반장').groupby([df['학년'], df['반']]).transform('any')
df[cond2]

   학년  반   직책   학생코드  점수
0   1  A   반장  물리001  94
1   1  A  부반장  화학001  90
4   1  B  부반장  물리003  86
5   1  B   반장  화학003  75
6   1  B   반원  화학004  80

그루퍼는 코드를 깔끔하게 전개하고 원본 데이터를 변환하지 않는 것이 장점

# 13. 시계열 데이터
# 13.1 시계열 데이터 소개
시계열 데이터는 시간의 흐름에 따라 수집된 데이터를 의미함\
대부분의 데이터는 시간의 흐름에 따라 발생하기에 시계열 데이터를 다루는 기능을 익히는 것은 중요함\
판다스는 금융 데이터를 다루고자 만들어진 라이브러리이기에 시계열 데이터 처리에 특화되어 있음\
이번 장에서는 시계열 데이터로의 변환, 생성 그리고 시계열에서 가장 중요한 함수인 시계열 데이터 기반의 그룹화 함수 resample 학습

### 13.1.1 시계열 데이터의 종류
판다스에서 주로 다루는 시계열 데이터는 timestamp, period, timedelta 세 종류가 있음

timestamp는 특정 시점을 가리키는 시계열 데이터\
기본적으로 날짜와 시간이 모두 표기되며 표기 가능한 최소 시간 단위는 ns(nano second)

period는 timestamp 사이의 기간을 나타내는 시계열 데이터\
타임 스탬프가 1달 간격이라면 period는 2022년 1월을 뜻하는 2022-01로 표현되며 해당 기간을 전부 포함한다는 의미

timedelta는 타임스탬프 사이의 시간 차이를 나타내는 시계열 데이터\
두 시점의 정확한 시간 차이는 31 days 00:00:00이며 이러한 시간 차이를 timedelta라고 함

세 종류의 시계열 데이터는 모두 각자의 쓰임이 있으며 세 자료형에 모두 숙달되면 편리함\
period와 timedelta는 다른 자료형으로 대체해서 다룰 수 있기에 시계열에서 가장 중요한 학습 목표는 timestamp 데이터를 다루는 것

### 13.1.2 datetime 자료형
timestamp와 datetime의 관계\
1640962800 $\rightarrow$ 정수 형식의 timestamp\
2022-01-01 00:00:00 $\rightarrow$ 날짜와 형식의 timestamp (datetime)\
timestamp를 날짜와 시간 형식으로 표현한 자료형이 datetime 자료형

datetime의 출력\
원칙적으로 datetime은 timestamp(시점)를 나타내기에 날짜와 시간이 모두 출력됨\
ex) 2022-01-01 00:10:01\
다만 모든 데이터가 00:00:00이라면 시간을 생략하고 날짜만 출력\
ex) 2022-01-01 00:00:00 $\rightarrow$ 2022-01-01

### 13.1.3 시계열 데이터의 학습 주안점
1. 변환(to_datetime)
2. 주기
3. 생성(date_range)
4. 그룹화와 그룹 집계(resample)
5. 특정 시계열 데이터 추출(dt 접근자와 다양한 메서드)

먼저 시계열 데이터로 변환하는 방법을 배우는데 특히 datetime 자료형으로 변환해야 하며 시리즈는 to_datetime 함수로 변환함\
파일에서 데이터 프레임으로 불러올 때 datetime 자료형으로 미리 지정할 수도 있는데 이때는 매개변수 parse_dates를 사용함

다음으로 시계열 데이터의 생성과 그룹화에 쓰일 주기를 알아야 하며 학습된 주기를 기반으로 시계열 데이터를 생성하는 것도 학습함

주기를 기반으로 일명 시계열의 groupby 함수라 불리는 resample 함수를 사용해 시계열 데이터를 손쉽게 그룹화하는 방법도 학습함\
resample 함수를 숙지하는 것이 시계열 단원에서 초반 목표

마지막으로 시계열 데이터에서 특정 데이터만 추출하고자 dt 접근자와 함께 사용되는 다양한 속성과 메서드를 활용\
특히 dt.strftime 함수로 datetime 자료형을 원하는 형태의 문자열로도 바꿀 수 있음

## 13.2 시계열 데이터로 변환 및 인덱싱
### 13.2.1 시계열 데이터로 변환하기(to_datetime)
판다스 to_datetime\
datetime 자료형으로 변환하는 함수
```py
to_datetime 함수의 주요 매개변수와 인수, 기본값
pd.to_datetime(arg, errors='raise', utc=False, format=None, origin='unix')
```
* arg : datetime으로 변환할 데이터를 입력하며, 단일 값이거나 1차원 배열만 가능함
* errors : 변환 불가능한 데이터를 처리하는 방법을 지정함
* utc : 시간대(timezone)가 포함된 데이터를 협정 세계시(UTC)로 변환할지 지정함
* format : 문자열의 날짜 표기 형식을 지정함
* unit : timestamp가 숫자로 주어질 때 숫자의 기본 단위를 지정하며, 기본값은 'ns'
* origin : timestamp가 숫자로 주어질 때 기준 날짜를 지정함

In [110]:
import pandas as pd
data = ['2023-01-01', '2023-02-02', '2023-03-02', '2023-04-10', '2023-05-31']
s = pd.Series(data)
s1 = pd.Series(['2022-01-03', '김판다'])
s

0    2023-01-01
1    2023-02-02
2    2023-03-02
3    2023-04-10
4    2023-05-31
dtype: object

시리즈 s1을 datetime 자료형으로 변환하는데 to_datetime 함수는 메서드로 사용할 수 없고 함수 pd.to_datetime 형태로 사용함

In [111]:
pd.to_datetime(s)

0   2023-01-01
1   2023-02-02
2   2023-03-02
3   2023-04-10
4   2023-05-31
dtype: datetime64[ns]

to_datetime 함수는 단일 값 또는 1차원 배열만 인수로 입력되어 시리즈만 변환함\
데이터 프레임에서 여러 열의 시계열 데이터를 가질 때가 흔하지 않고, apply 함수를 이용하면 데이터 프레임 전체에 적용할 수 있기 때문

to_datetime 함수에 errors='coerce'를 입력하면 변환 불가능한 데이터가 섞여 있을 때 NaT로 변환하고, 나머지 데이터를 datetime으로 변환하는데 NaT(Not a Time)는 시계열 데이터에서 사용되는 null

In [112]:
print(s1, '\n') # s1과 빈 행을 출력하는 코드
pd.to_datetime(s1, errors='coerce')

0    2022-01-03
1           김판다
dtype: object

0   2022-01-03
1          NaT
dtype: datetime64[ns]

### 13.2.2 기타 시계열 변환 함수들
판다스에는 timestamp뿐 아니라 period와 timedelta 자료형이 있기에 다양한 시계열 변환 함수가 존재함

||timestamp|period|timedelta|
|:--|:--|:--|:--|
|단일 값 생성|pd.Timestamp|pd.Period|pd.Timedelta|
|배열 생성|pd.date_range|pd.period_range|pd.timedelta_range|
|변환|pd.to_datetime|to_period|pd.to_timedelta|

In [113]:
# 시계열 데이터 날짜를 2일씩 더하기
s2 = pd.to_datetime(s)
s2 + pd.Timedelta('2 day')

0   2023-01-03
1   2023-02-04
2   2023-03-04
3   2023-04-12
4   2023-06-02
dtype: datetime64[ns]