# chapter 8. 열 가공하기
## 8.1 열 가공하기
### 8.1.1 열 가공하기란?
열 가공하기는 데이터 전처리 과정에서 새로운 관측치를 추가하지 않고 주어진 데이터를 업무에 더 효율적인 데이터로 만드는 과정\
원시 데이터에서 행은 각 사례(instacne)를 의미하고, 열은 주로 데이터의 특성(feature)를 의미함\
독립변인이나 종속변인으로 사용되는 것이 특성임\
안타와 홈런이라는 특성으로는 적중률 특성과 관계가 높은 특성을 찾지 못하였는데, 타수와 안타라는 특성을 이용해 새로운 특성인 타율을 생성하니 적중률과 관계가 높은 특성을 찾을 수 있었다면, 데이터 전처리 과정에서 추가 데이터 수집 없이 주어진 데이터를 더 적합한 데이터로 만들었다고 할 수 있으며 이를 열 가공하기라고 함

### 8.1.2 다양한 열 가공하기 소개
각 열의 연산을 하거나 통계 함수를 사용하거나 불리언 마스킹과 데이터의 범주화로도 새로운 특성을 만드는 열 가공하기를 수행할 수 있음

## 8.2 다양한 연산으로 열 가공하기
### 8.2.1 객체 간 연산으로 열 가공하기

In [36]:
import pandas as pd
data1 = [['A', 0.1, 50, 0, 5], ['B', 0.25, 400, 40, 99],
         ['C', 0.35, 100, 10, 36], ['D', 0.3, 300, 4, 91]]
df1 = pd.DataFrame(data1, columns=['선수', '적중률', '타수', '홈런', '안타'])
df1

  선수   적중률   타수  홈런  안타
0  A  0.10   50   0   5
1  B  0.25  400  40  99
2  C  0.35  100  10  36
3  D  0.30  300   4  91

In [37]:
df1['타율'] = df1['안타'] / df1['타수']
df1

  선수   적중률   타수  홈런  안타        타율
0  A  0.10   50   0   5  0.100000
1  B  0.25  400  40  99  0.247500
2  C  0.35  100  10  36  0.360000
3  D  0.30  300   4  91  0.303333

### 8.2.2 객체 내 연산으로 열 가공하기

In [38]:
data2 = [[10, 0, 20], [30, 30, 40], [0, 20, 10], [30, 10, 10]]
idx = ['2024-05-01', '2024-05-02', '2024-05-03', '2024-05-04']
df2 = pd.DataFrame(data2, index=idx, columns=['A품목', 'B품목', 'C품목'])
df2

            A품목  B품목  C품목
2024-05-01   10    0   20
2024-05-02   30   30   40
2024-05-03    0   20   10
2024-05-04   30   10   10

In [39]:
df2['일판매량'] = df2.sum(axis=1)
df2['누적판매'] = df2['일판매량'].cumsum()
df2

            A품목  B품목  C품목  일판매량  누적판매
2024-05-01   10    0   20    30    30
2024-05-02   30   30   40   100   130
2024-05-03    0   20   10    30   160
2024-05-04   30   10   10    50   210

### 8.2.3 수학적 연산으로 열 가공하기

In [40]:
df3 = pd.DataFrame([[1, 2], [2, 4], [3, 8], [4, 16]], columns=['x', 'y'])
df3

   x   y
0  1   2
1  2   4
2  3   8
3  4  16

In [41]:
import numpy as np
# pd.options.display.float_format = '{:.3f}'.format # 소수점 셋째 자리 출력
df3['log_y'] = np.log(df3['y'])
df3

   x   y     log_y
0  1   2  0.693147
1  2   4  1.386294
2  3   8  2.079442
3  4  16  2.772589

## 8.3 순위 매기기
수치형 데이터의 값보다 순위나 백분위수가 분석 목적에 더욱 적함할 때도 있으며 판다스의 rank 함수를 이용할 수 있음

### 8.3.1 순위 매기기(rank)
판다스 rank\
데이터 프레임이나 시리즈의 순위를 매기는 함수
```py
rank 함수의 주요 매개변수와 인수, 기본값
df.rank(method='average', ascending=True, pct=False)
```
* method : 동점자 처리 방식을 지정함
* ascending : 오름차순과 내림차순을 지정하며 기본값은 오름차순
* pct : 순위를 반환할지 백분위수(percentile)를 반환할지 지정하며 기본값이 False이기에 순위를 반환하며 True는 백분위수 반환

In [42]:
import pandas as pd
# pd.options.display.float_format = None # 소수점 출력 옵션 리셋
s = pd.Series([90, 70, 80, 60], index=list('ABCD'))
s

A    90
B    70
C    80
D    60
dtype: int64

In [43]:
s.rank()

A    4.0
B    2.0
C    3.0
D    1.0
dtype: float64

In [44]:
s.rank(ascending=False).astype('int')

A    1
B    3
C    2
D    4
dtype: int64

In [45]:
s.rank(pct=True)

A    1.00
B    0.50
C    0.75
D    0.25
dtype: float64

### 8.3.2 rank 함수의 다양한 동점자 처리 방식
|인수|동점자 처리 방식|
|:--|:--|
|'average'|평균 순위(두 명이 공등 1등일 때 모두 1.5등), 기본값|
|'min'|최저 순위(두 명이 공동 1등일 때 모두 1등)|
|'max'|최대 순위(두 명이 공동 1등일 때 모두 2등)|
|'first'|순서에 따른 순위(두 명이 공동 1등일 때 먼저 출현한 행이 1등)|
|'dense'|밀집한 순위('min'과 비슷하나 공동 1등이 존재해도 다음 순위로 2등을 부여)|

In [46]:
import pandas as pd
data = [['김판다', 82, 17], ['권보아', 95, 17], ['강승주', 95, 18],
        ['안지선', 72, 18], ['조민영', 72, 19], ['최진환', 95, 19]]
df = pd.DataFrame(data, columns=['이름', '점수', '나이'])
df

    이름  점수  나이
0  김판다  82  17
1  권보아  95  17
2  강승주  95  18
3  안지선  72  18
4  조민영  72  19
5  최진환  95  19

In [47]:
df['average'] = df['점수'].rank(ascending=False)
df['min'] = df['점수'].rank(ascending=False, method='min')
df['max'] = df['점수'].rank(ascending=False, method='max')
df['first'] = df['점수'].rank(ascending=False, method='first')
df['dense'] = df['점수'].rank(ascending=False, method='dense')
df

    이름  점수  나이  average  min  max  first  dense
0  김판다  82  17      4.0  4.0  4.0    4.0    2.0
1  권보아  95  17      2.0  1.0  3.0    1.0    1.0
2  강승주  95  18      2.0  1.0  3.0    2.0    1.0
3  안지선  72  18      5.5  5.0  6.0    5.0    3.0
4  조민영  72  19      5.5  5.0  6.0    6.0    3.0
5  최진환  95  19      2.0  1.0  3.0    3.0    1.0

## 8.4 불리언 마스킹
True, False에 따라 값을 부여하는 것이 불리언 마스킹(boolean masking)\
불리언 마스킹은 불(bool)에 따라 값을 씌운다(mask)는 의미\
기존에 수집된 데이터를 조건에 따라 새로운 값으로 만들어 유용한 열 가공 기법임

### 8.4.1 불리언 인덱싱으로 불리언 마스킹
불리언 인덱싱을 수행한 후 새로운 값을 배정하는 것은 가장 기본적인 형태의 불리언 마스킹임

In [48]:
import pandas as pd
data = {'국어': {'가': 86, '나': 79, '다': 93, '라': 80},
        '영어': {'가': 90, '나': 10, '다': 50, '라': 95}}
df = pd.DataFrame(data)
df

   국어  영어
가  86  90
나  79  10
다  93  50
라  80  95

In [49]:
df1 = df.copy()
df1.loc[df1['영어'] >= 90, '영어평점'] = 4.5
df1

   국어  영어  영어평점
가  86  90   4.5
나  79  10   NaN
다  93  50   NaN
라  80  95   4.5

### 8.4.2 판다스 함수로 불리언 마스킹(mask, where)
판다스 mask\
조건문이 True인 부분의 값을 변환하는 함수, 즉 불리언 마스킹을 수행하는 함수

판다스 where\
조건문이 False인 부분의 값을 변환하는 함수, 즉 불리언 마스킹을 수행하는 함수
```py
mask 함수의 주요 매개변수와 인수, 기본값
df.mask(cond, other=nan)
```
* cond : 조건문처럼 작동하는 True와 False의 배열을 입력함
* other : 조건문이 True일 때 변환될 값을 지정하며 기본값은 NaN

mask와 where 함수는 시리즈와 데이터 프레임에 모두 적용됨\
주로 시리즈에 적용하므로 시리즈를 대상으로 실습할 것임\
mask 함수를 적용하고 조건문을 입력하면 입력된 조건문이 True인 위치가 NaN으로 변환되며 where 함수는 조건문이 False인 위치가 NaN으로 변환됨

In [50]:
df

   국어  영어
가  86  90
나  79  10
다  93  50
라  80  95

In [51]:
df['국어'].mask(df['국어'] < 80)

가    86.0
나     NaN
다    93.0
라    80.0
Name: 국어, dtype: float64

In [52]:
cond1 = df['국어'] < 80
df['국어'].where(cond1)

가     NaN
나    79.0
다     NaN
라     NaN
Name: 국어, dtype: float64

In [53]:
df['국어'].mask(~cond1)

가     NaN
나    79.0
다     NaN
라     NaN
Name: 국어, dtype: float64

In [54]:
df['국어'].mask(cond1, other='낙제')

가    86
나    낙제
다    93
라    80
Name: 국어, dtype: object

In [55]:
cond2 = df['영어'] >= 90
df['국어'].mask(cond2, df['국어'] + 2)

가    88
나    79
다    93
라    82
Name: 국어, dtype: int64

In [56]:
df['국어'].where(cond2).mean()

np.float64(83.0)

### 8.4.3 넘파이의 np.where 함수로 불리언 마스킹

In [57]:
df2 = df.copy()
df2['국어'].mask(cond1, '낙제').mask(~cond1, '이수')

가    이수
나    낙제
다    이수
라    이수
Name: 국어, dtype: object

mask 함수는 하나의 값을 부여할 때마다 mask 함수를 한 번 사용해야 하고, True와 False에 각각 값을 부여하기에 두 번의 mask 함수를 사용해야 하는 불편함이 존재함

넘파이 np.where\
True와 False에 따라 각각 값을 부여하는 함수
```py
np.where 함수의 주요 매개변수와 인수, 기본값
np.where(condition, x, y)
```
* condition : 불(bool)자료형 배열을 입력하는데, 즉 조건문을 입력받는 매개변수
* x : True일 때 부여할 값을 입력하며 단일 값 또는 배열을 입력함
* y : False일 때 부여할 값을 입력하며 단일 값 또는 배열을 입력함

In [58]:
import numpy as np
np.where(cond1, '낙제', '이수')

array(['이수', '낙제', '이수', '이수'], dtype='<U2')

In [59]:
df2['국어평가'] = np.where(cond1, '낙제', '이수')
df2

   국어  영어 국어평가
가  86  90   이수
나  79  10   낙제
다  93  50   이수
라  80  95   이수

### 8.4.4 넘파이의 np.select 함수로 불리언 마스킹
np.where 함수를 사용하면 True, False에 따라 각기 다른 두 개의 값이 편리하게 부여됨\
이번에는 조건에 따라 세 종류의 값을 부여해 보자\
국어가 90점 이상이면 A, 80점 이상이면 B, 80점 미만이면 C를 부여함

In [60]:
df3 = df.copy()
cond3 = df3['국어']>=90
cond4 = df3['국어']>=80

In [61]:
np.where(cond4, np.where(cond3, 'A', 'B'), 'C')

array(['B', 'C', 'A', 'B'], dtype='<U1')

In [62]:
df3['국어'].mask(cond3, 'A').mask(~cond3 & cond4, 'B').mask(~cond4, 'C')

가    B
나    C
다    A
라    B
Name: 국어, dtype: object

mask 함수를 세 번 사용하면 A, B, C의 학점이 부여됨\
더 많은 조건문으로 더 많은 종류의 값을 부여하면 코드가 복잡해지고 가독성이 떨어지며 코드의 작성도 어려워짐\
불리언 마스킹으로 3 종류 이상의 값을 반환할 때는 np.where, mask 함수 모두 불편한데 이때는 np.select 함수를 사용함

넘파이 np.select\
여러 개의 조건문을 입력해 각 조건에 해당하는 값을 반환하는 함수
```py
np.select(condlist, choicelist, default=0)
```
* condlist : 조건문들을 리스트로 묶어 입력함
* choicelist : 조건문을 만족할 때 반환할 값을 리스트로 묶어 입력함
* default : condlist의 모든 조건에서 False일 때 부여할 값을 지정함

np.select 함수는 불리언 마스킹 결과 여러 종류의 값을 반환해야 할 때 사용함\
매개변수 condlist에 조건문을 리스트로 묶어 입력하고, 매개변수 choicelist에 각 조건을 맞추어 반환해야 할 값들을 리스트로 묶어 입력하면 각 조건에 맞추어 지정한 값이 반환됨\
매개변수 default로 어느 조건에도 해당하지 않을 때 부여할 값도 설정할 수 있음

In [63]:
np.select([cond3, ~cond3&cond4], ['A','B'],'C')

array(['B', 'C', 'A', 'B'], dtype='<U1')

In [64]:
# cond3와 cond4를 모두 만족할 때는 더 왼쪽에 위치한 cond3의 값인 'A'를 부여하기에 이렇게 작성하여도 됨
np.select([cond3, cond4], ['A','B'],'C')

array(['B', 'C', 'A', 'B'], dtype='<U1')

In [65]:
df3['국어학점'] = np.select([cond3, cond4], ['A','B'],'C')
df3

   국어  영어 국어학점
가  86  90    B
나  79  10    C
다  93  50    A
라  80  95    B

In [66]:
cond4 = df3['국어'] >= 80
cond5 = df3['영어'] >= 80
df3['학생평가'] = np.select([cond4 & cond5, cond4 | cond5], ['수','우'],'미')
df3

   국어  영어 국어학점 학생평가
가  86  90    B    수
나  79  10    C    미
다  93  50    A    우
라  80  95    B    수

## 8.5 수치형 데이터의 범주화
데이터 분석을 하면 수치형 데이터를 범주형(category) 데이터로 변환해야 할 때가 있음\
앞 예제에서 부여한 학점은 수치형 데이터를 범주형 데이터로 변환한 전형적인 예시\
불리언 마스킹으로도 간단한 범주화가 가능하지만, 범주화 그룹이 많아질수록 코드가 복잡해짐\
판다스는 수치형 데이터를 범주형 데이터로 변환하는 함수로 cut과 qcut이 있으며, cut 함수는 수치를 기준으로 범주화하고, qcut 함수는 백분위수를 기준으로 범주화함

### 8.5.1 수치로 구간을 나누어 범주화(cut)
판다스 cut\
수치를 기준으로 구간을 나누어 범주화(categorization)하는 함수

```py
cut 함수의 주요 매개변수와 인수, 기본값
pd.cut(x, bins, right=True, labels=None)
```
* x : 범주화를 수행할 배열을 입력하며 반드시 1차원이어야 함
* bins : 구간을 나누는 기준을 입력하며 정수를 입력하면 균등 분할함
* right : 구간에서 우측 경계를 포함할지 여부를 지정함
* labels : 구간의 이름을 지정하며 bins로 생성된 구간 개수와 같아야 함

cut 함수는 수치를 기준으로 구간을 나누어 범주화하는 함수이며, 이 함수는 메서드로 사용할 수 없기에 반드시 pd.cut 함수 형태로 입력\
bins는 구간을 지정하며 정수를 입력하면 입력된 개수만큼 균등 분할, 수치의 경계를 리스트로 입력하면 입력된 경계로 구간을 분할

In [67]:
pd.cut(df['국어'], bins=[0, 80, 90, 100])

가     (80, 90]
나      (0, 80]
다    (90, 100]
라      (0, 80]
Name: 국어, dtype: category
Categories (3, interval[int64, right]): [(0, 80] < (80, 90] < (90, 100]]

bins에 수치의 경계를 4개 입력하면 3개의 범주로 나뉘고, 기본값으로 각 구간은 우측 경계를 포함\
결과는 카테고리 자료형으로 반환되는데 카테고리 자료형은 일반적인 문자열과 다르며 astype 함수로 문자열로 변환할 수 있음

In [68]:
pd.cut(df['국어'], bins=[0, 80, 90, 100], labels=['C', 'B', 'A'])

가    B
나    C
다    A
라    C
Name: 국어, dtype: category
Categories (3, object): ['C' < 'B' < 'A']

하나의 수치형 자료형인 열을 기준으로 범주화를 수행할 때는 불리언 마스킹에 비해 cut 함수가 더 편리함

### 8.5.2 백분위수로 구간을 나누어 범주화(qcut)
판다스 qcut\
백분위수를 기준으로 구간을 나누어 범주화하는 함수
```py
qcut 함수의 주요 매개변수와 인수, 기본값
pd.qcut(x, q, right=True, labels=None)
```
* x : 범주화를 수행할 배열을 입력하며 반드시 1차원 배열이어야 함
* q : 구간을 나누는 기준을 입력하며 정수를 입력하면 균등 분할함

In [69]:
pd.qcut(df['영어'], q=[0, 0.25, 0.75, 1], labels=['C', 'B', 'A'])

가    B
나    C
다    B
라    A
Name: 영어, dtype: category
Categories (3, object): ['C' < 'B' < 'A']

## 8.6 결측값 처리하기 2
fillna 함수로 결측값을 대체할 수 있는데, 이번 절에서는 더 심화된 결측값 대체 방법을 학습할 것임

### 8.6.1 전후방의 데이터로 결측값 대체하기
판다스 ffill, bfill\
전후방의 데이터로 결측값을 대체하는 함수
```py
ffill 함수의 주요 매개변수와 인수, 기본값
df.ffill(axis=0, limit=None)
```
* axis : 축을 지정하고 기본값은 0이며 열의 전방 데이터로 NaN을 대체함
* limit : 대체할 최대 연속 NaN의 개수를 제한함

In [70]:
import pandas as pd
data1 = {'A': [float('nan'), 2, float('nan')], 'B': [0, float('nan'), 4],
         'C': [1, float('nan'), 5], 'D': [float('nan'), 3, 6]}
df1 = pd.DataFrame(data1)
df1

     A    B    C    D
0  NaN  0.0  1.0  NaN
1  2.0  NaN  NaN  3.0
2  NaN  4.0  5.0  6.0

In [71]:
df1.ffill()

     A    B    C    D
0  NaN  0.0  1.0  NaN
1  2.0  0.0  1.0  3.0
2  2.0  4.0  5.0  6.0

In [72]:
df1.ffill(axis=1)

     A    B    C    D
0  NaN  0.0  1.0  1.0
1  2.0  2.0  2.0  3.0
2  NaN  4.0  5.0  6.0

In [73]:
df1.bfill()

     A    B    C    D
0  2.0  0.0  1.0  3.0
1  2.0  4.0  5.0  3.0
2  NaN  4.0  5.0  6.0

In [74]:
df1.bfill(axis=1, limit=1)

     A    B    C    D
0  0.0  0.0  1.0  NaN
1  2.0  NaN  3.0  3.0
2  4.0  4.0  5.0  6.0

### 8.6.2 결측값 보간하기(interpolate)
판다스 interpolate\
보간법을 사용하여 결측값을 대체하는 함수
```py
interpolate 함수의 주요 매개변수와 인수, 기본값
df.interpolate(method='linear', axis=0)
```
* method : 사용할 보간법을 지정하며 기본값은 'linear'이고 선형 보간법
* axis : 축을 지정함

In [75]:
import pandas as pd
s = pd.Series([0, 1, float('nan'), 3], index=list('ABCD'))
s

A    0.0
B    1.0
C    NaN
D    3.0
dtype: float64

In [76]:
s.interpolate()

A    0.0
B    1.0
C    2.0
D    3.0
dtype: float64

## 8.7 행 간의 연산으로 열 가공하기
### 8.7.1 데이터 이동하기
판다스 shift\
데이터를 저앻진 칸만큼 이동시키는 함수
```py
shift 함수의 주요 매개변수와 인수, 기본값
df.shift(periods=1, freq=None, axis=0)
```
* periods : 이동할 칸 수를 지정하며 기본값은 한 칸 이동
* freq : 시계열 데이터를 이동할 때 이동 주기를 지정함
* axis : 축을 지정해 이동 방향을 지정함

In [77]:
import pandas as pd
data = {'날짜': ['01/01', '01/02', '01/03', '01/04', '01/05'],
        '가격': [1000, 1200, 900, 1200, 1500]}
df = pd.DataFrame(data, columns=['날짜', '가격'])
df

      날짜    가격
0  01/01  1000
1  01/02  1200
2  01/03   900
3  01/04  1200
4  01/05  1500

In [78]:
df['가격'].shift()

0       NaN
1    1000.0
2    1200.0
3     900.0
4    1200.0
Name: 가격, dtype: float64

In [79]:
df['가격'] - df['가격'].shift()

0      NaN
1    200.0
2   -300.0
3    300.0
4    300.0
Name: 가격, dtype: float64

### 8.7.2 행 간의 차이 구하기(diff)
판다스 diff\
행 간의 연산으로 차이를 구하는 함수이며 매개변수와 인수는 shift와 동일함

In [80]:
df['가격'].diff()

0      NaN
1    200.0
2   -300.0
3    300.0
4    300.0
Name: 가격, dtype: float64

In [81]:
df['가격'].diff(2)

0      NaN
1      NaN
2   -100.0
3      0.0
4    600.0
Name: 가격, dtype: float64

diff 함수가 간편하지만 diff 함수는 뺄셈만 수행하고 shift 함수는 다양한 연산 결과를 수행할 수 있다는 차이가 존재함

### 8.7.3 행 간의 변동률 구하기
판다스 pct_change\
행 각의 연산으로 변동률을 구하는 함수

In [82]:
df['가격'].pct_change()

0         NaN
1    0.200000
2   -0.250000
3    0.333333
4    0.250000
Name: 가격, dtype: float64

# 9. apply
## 9.1 apply 함수 소개
### 9.1.1 apply 함수가 필요한 이유
판다스 내장 함수로 수행할 수 없는 기능이 apply 함수를 이용하면 가능함

### 9.1.2 apply 함수의 기능
apply 함수는 함수를 적용하기 위한 함수\
apply 함수는 판다스 함수가 아닌 함수도 시리즈의 각 셀에 적용하게 하며 시리즈에만 적용하는 함수를 데이터 프레임 전체에 적용하게 함\
각 요소에만 적용되는 함수를 반복해서 적용해 전체에 적용하는 함수가 apply 함수이며 반복문인 for 문 대신 사용하는 함수라 봐도 됨

## 9.2 시리즈에 apply 함수 적용하기
apply 함수는 시리즈와 데이터 프레임 모두 적용이 가능한 함수이지만 적용 방식이 서로 다름

### 9.2.1 시리즈에 apply 함수 적용하기

In [83]:
import pandas as pd
data = {'이름': ['강승주', '송중기', '권보아', '김판다'],
        '답안': ['mom', 'get', 'pandas', 'level']}
df = pd.DataFrame(data)
df

    이름      답안
0  강승주     mom
1  송중기     get
2  권보아  pandas
3  김판다   level

시리즈 각 셀에 작성된 글자 수의 길이를 구하려면 어떻게 해야할까?

In [84]:
len(df['답안'])

4

len 함수는 문자열의 길이를 반환할 뿐, 시리즈에 적용해 각 셀의 글자 수를 시리즈로 반환하지는 않음\
시리즈에 len 함수를 적용하면 각 셀에서 문자열의 길이를 담은 시리즈를 반환하는 것이 아니라 시리즈의 길이를 반환함\
이럴 때 apply로 len 함수를 적용하면, 각 셀의 글자 수를 나타내는 시리즈가 반환됨

In [85]:
df['답안'].apply(len)

0    3
1    3
2    6
3    5
Name: 답안, dtype: int64

In [87]:
df['글자수'] = df['답안'].apply(len)
df

    이름      답안  글자수
0  강승주     mom    3
1  송중기     get    3
2  권보아  pandas    6
3  김판다   level    5

### 9.2.2 사용자 정의 함수와 apply
df는 4글자 이상의 회문을 제시하라는 문제에 대한 학생들의 답안이었기에 회문 여부를 확인하려고 답안을 역순으로 변환했을 때 원본과 동일한지 여부를 확인

In [88]:
def rev1(x):
    return x[::-1]

df['답안'].apply(rev1)

0       mom
1       teg
2    sadnap
3     level
Name: 답안, dtype: object

### 9.2.3 lambda 함수와 apply
파이썬은 한 번만 사용할 사용자 정의 함수를 간편하게 지정하는 방법으로 lambda 함수를 사용함

In [89]:
df['답안'].apply(lambda x : x[::-1])

0       mom
1       teg
2    sadnap
3     level
Name: 답안, dtype: object

In [91]:
df['역순'] = df['답안'].apply(lambda x : x[::-1])
df

    이름      답안  글자수      역순
0  강승주     mom    3     mom
1  송중기     get    3     teg
2  권보아  pandas    6  sadnap
3  김판다   level    5   level

In [92]:
cond1 = df['글자수'] >= 4
cond2 = df['답안'] == df['역순']
df[cond1 & cond2]

    이름     답안  글자수     역순
3  김판다  level    5  level

### 9.2.4 시리즈에 apply 함수 적용할 때 유의할 점
apply 함수는 반복 연산을 수행하기에 시리즈에 무분별하게 apply 함수를 적용하면 벡터화 연산을 사용할 수 없어 비효율적인 코드가 됨\
따라서 벡터화 연산이 가능할 때는 apply 함수를 사용하지 않아야 함

### 9.2.5 lambda 함수 추가 학습

In [93]:
s = pd.Series(['cat01', 'dog02', 'bird03'])
s

0     cat01
1     dog02
2    bird03
dtype: object

In [95]:
x = s[0]
x

'cat01'

In [96]:
x[:-2]

'cat'

In [97]:
s.apply(lambda x : x[:-2])

0     cat
1     dog
2    bird
dtype: object

In [100]:
s.apply(lambda x : 'O' if len(x) == 5 else 'X')

0    O
1    O
2    X
dtype: object

## 9.3 데이터 프레임에 apply 함수 적용하기
### 9.3.1 데이터 프레임에 apply 함수 적용하기

In [101]:
import pandas as pd
data = {'국어': {'A': '87', 'B': '70', 'C': '98', 'D': '-'},
        '영어': {'A': '-', 'B': '72', 'C': '76', 'D': '77'},
        '수학': {'A': '70', 'B': '73', 'C': '-', 'D': '95'}}
df = pd.DataFrame(data)
df

   국어  영어  수학
A  87   -  70
B  70  72  73
C  98  76   -
D   -  77  95

df를 수치형 자료형으로 변환하려면, astype 함수는 사용할 수 없고 to_numeric 함수를 사용해야 함

In [102]:
pd.to_numeric(df['국어'], errors='coerce')

A    87.0
B    70.0
C    98.0
D     NaN
Name: 국어, dtype: float64

to_numeric 함수는 시리즈에만 적용해 df 전체에 적용할 수 없는데, 이때 apply 함수를 사용하면 시리즈에만 적용되는 함수가 데이터 프레임 전체에 적용됨\
단 to_numeric 함수는 매개변수 errors에 'coerce'를 입력해야하는데, 추가 매개변수에 인수를 전달해야 하는 함수를 apply 함수로 적용할 때는 apply 함수에 입력함

In [103]:
df.apply(pd.to_numeric, errors='coerce')

     국어    영어    수학
A  87.0   NaN  70.0
B  70.0  72.0  73.0
C  98.0  76.0   NaN
D   NaN  77.0  95.0

### 9.3.2 데이터 프레임에 apply 함수 적용할 때 축 지정
* axis=0 : 기본값이며, 각 열마다 함수를 적용함
* axis=1 : 각 행마다 함수를 적용함

In [104]:
data1 = {'국어': {'A': 90, 'B': 70, 'C': 80, 'D': float('nan')},
         '영어': {'A': float('nan'), 'B': 90, 'C': 80, 'D': 90},
         '수학': {'A': 20, 'B': 50, 'C': float('nan'), 'D': 40}}
df1 = pd.DataFrame(data1)
df1

     국어    영어    수학
A  90.0   NaN  20.0
B  70.0  90.0  50.0
C  80.0  80.0   NaN
D   NaN  90.0  40.0

In [105]:
x = df1['국어']
x

A    90.0
B    70.0
C    80.0
D     NaN
Name: 국어, dtype: float64

In [106]:
x.fillna(x.min())

A    90.0
B    70.0
C    80.0
D    70.0
Name: 국어, dtype: float64

In [107]:
df1.apply(lambda x : x.fillna(x.min()))

     국어    영어    수학
A  90.0  80.0  20.0
B  70.0  90.0  50.0
C  80.0  80.0  20.0
D  70.0  90.0  40.0

In [108]:
df1.apply(lambda x : x.fillna(x.min()), axis=1)

     국어    영어    수학
A  90.0  20.0  20.0
B  70.0  90.0  50.0
C  80.0  80.0  80.0
D  40.0  90.0  40.0

### 9.3.3 복수 열의 데이터를 입력하는 lambda 함수를 각 행에 적용하기

### 9.3.4 apply와 map 함수 비교

In [109]:
data3 = [['noon', 'esse', 'rotor'], ['mom', 'marram', 'keek'],
         ['dad', 'nun', 'poop'], ['level', 'pullup', 'otto']]
df3 = pd.DataFrame(data3, index=list('ABCD'), columns=['1회', '2회', '3회'])
df3

      1회      2회     3회
A   noon    esse  rotor
B    mom  marram   keek
C    dad     nun   poop
D  level  pullup   otto

apply를 사용하면 하나의 열에서 글자 수를 반환할 수 있으며, map 함수를 사용해도 하나의 열에서 글자 수를 반환할 수 있음\
map 함수는 매퍼가 입력되면 매핑을 수행하는 함수이며 주로 딕셔너리나 시리즈를 매퍼로 활용하지만 함수도 매퍼로 활용함\
따라서 map 함수를 이용하여 글자 수를 반환하는 len 함수를 적용하면 시리즈의 각 셀의 글자 수가 반환됨

In [110]:
df3['1회'].map(len)

A    4
B    3
C    3
D    5
Name: 1회, dtype: int64

map 함수를 시리즈에 적용하면 apply 함수를 시리즈에 적용한 것과 같은 결과를 얻음\
시리즈에 apply 함수를 적용할 때는 map 함수를 대신 사용해도 됨\
map 함수는 매퍼로 함수뿐 아니라 딕셔너리와 시리즈도 입력되기에 시리즈에 적용할 때는 apply 함수보다 더 다양한 기능을 수행함\
또한 map 함수는 시리즈뿐 아니라 인덱스 클래스에도 적용할 수 있는 장점이 존재함\
다만 map 함수는 시리즈와 인덱스 클래스에만 적용이 가능하기에 df3 전체에 적용하지는 못함

In [111]:
df3.apply(lambda x : x.map(len))

   1회  2회  3회
A   4   4   5
B   3   6   4
C   3   3   4
D   5   6   4

|분류|map|apply|
|:--|:--|:--|
|적용 대상|시리즈, 인덱스 클래스|시리즈, 데이터 프레임|
|인수|함수, 시리즈, 딕셔너리 등의 매퍼|함수|
|인수로 입력된 함수 적용 대상|셀마다 함수 적용|시리즈에 적용할 때는 셀마다 함수 적용<br> 데이터 프레임에 적용할 때는 시리즈마다 함수 적용|

__apply를 사용할 때__
1. 기본 파이썬 내장 함수를 시리즈의 각 셀에 적용할 때
2. 시리즈에만 적용되는 판다스 함수를 데이터 프레임 전체에 적용할 때
3. 사용자 정의 함수나 다른 라이브러리의 함수로 1,2번을 수행할 때

# 10. 문자열 다루기
## 10.1 문자열을 다루는 함수
### 10.1.1 판다스의 문자열을 다루는 함수를 배우는 이유
apply 함수를 사용ㅇ하여 파이썬의 문자열 함수를 시리즈에 적용할 수 있음\
하지만 다른 자료형인 셀이 함께 섞여 있어도 판다스의 문자열 함수는 이를 간편하게 처리함

### 10.1.2 판다스의 문자열을 다루는 함수들의 특징
판다스의 문자열을 다루는 함수들의 특징
1. 시리즈나 인덱스 클래스를 대상으로 적용이 가능함 <br> 데이터 프레임 전체에 판다스의 문자열 함수를 사용하고 싶다면 apply와 lambda 함수의 조합으로 문자열 함수를 사용
2. str 접근자(accessor)에 메서드로 적용해야 함 <br> 적용할 시리즈에 str 접근자를 반드시 먼저 적용한 뒤 메서드를 입력해야 함
3. 함수의 이름은 파이썬에서 문자열을 다루는 함수와 거의 동일함
4. 문자열 함수를 적용할 수 없는 셀을 NaN으로 처리함 <br> 오브젝트 자료형은 문자열과 문자열이 아닌 자료형이 섞여 있거나 결측값을 포함할 때가 많음 <br> 그래서 apply 함수로 기본 파이썬의 문자열 함수를 적용하면 별도로 예외 처리를 할 때가 많음 <br> 반면 판다스의 문자열 함수는 예외 처리를 하지 않아도 예외는 NaN으로 변환하기에 훨씬 간편함
5. 별도의 라이브러리 없이 정규 표현식을 사용함

## 10.2 문자열을 다루는 다양한 함수
|함수|기능|
|:--|:--|
|str[ ]| 문자열이나 리스트 등을 인덱싱과 슬라이싱|
|str.len|문자열이나 리스트의 길이 반환|
|str.strip|문자열 좌우의 공백 제거(공백이 아닌 문자도 지정 가능)|
|str.lstrip|문자열 좌측 공백 제거(공백이 아닌 문자도 지정 가능)|
|str.rstrip|문자열 우측 공백 제거(공백이 아닌 문자도 지정 가능)|
|str.split|문자열 분할|
|str.replace|문자열 치환|
|str.upper|전부 대문자로 변환|
|str.lower|전부 소문자로 변환|
|str.contains|특정 문자열 포함 여부 확인|
|str.startswith|특정 문자열로 시작 여부 확인|
|str.endswith|특정 문자열로 마무리 여부 확인|
|str.extract|문자열 추출|
|str.extractall|패턴에 맞는 모든 문자열 추출|

### 10.2.1 인덱싱과 슬라이싱

In [112]:
import pandas as pd
data = {'문자열': ['A0', 'B1', 'C2', 'D3'],
        '문자열2': ['물리01', '물리02', '화학01', 99],
        '리스트': [['물리', 1], ['물리', 2], ['화학', 1], ['화학', 2]]}
df = pd.DataFrame(data)
df

  문자열  문자열2      리스트
0  A0  물리01  [물리, 1]
1  B1  물리02  [물리, 2]
2  C2  화학01  [화학, 1]
3  D3    99  [화학, 2]

In [113]:
df['문자열'].str[0]

0    A
1    B
2    C
3    D
Name: 문자열, dtype: object

In [114]:
df['문자열'].str[:2]

0    A0
1    B1
2    C2
3    D3
Name: 문자열, dtype: object

In [115]:
df['리스트'].str[0]

0    물리
1    물리
2    화학
3    화학
Name: 리스트, dtype: object

### 10.2.2 문자열의 길이 반환하기

In [116]:
s = pd.Series(['mom', 'get', 'pandas', 'level'])
s

0       mom
1       get
2    pandas
3     level
dtype: object

In [117]:
s.str.len()

0    3
1    3
2    6
3    5
dtype: int64

### 10.2.3 문자열의 공백 제거하기

In [118]:
data1 = {'col1':['  205', '12   '],
         'col2':['00205', '12000']}
df = pd.DataFrame(data1)
df

    col1   col2
0    205  00205
1  12     12000

In [119]:
df['col1'].str.strip()

0    205
1     12
Name: col1, dtype: object

In [120]:
df['col2'].str.strip('0')

0    205
1     12
Name: col2, dtype: object

### 10.2.4 문자열 분할하기

In [121]:
s = pd.Series(['a-001', 'b-002', 'cd-003'])
data1 = {'주소': ['서울특별시 용산구 독서당로',
                  '경상남도 남해군 옥천로12길 302호',
                  '경상남도 김해시 가야로47길']}
df = pd.DataFrame(data1)

In [122]:
s

0     a-001
1     b-002
2    cd-003
dtype: object

In [123]:
s.str.split('-')

0     [a, 001]
1     [b, 002]
2    [cd, 003]
dtype: object

In [124]:
s.str.split('-').str[0]

0     a
1     b
2    cd
dtype: object

In [125]:
df

                     주소
0        서울특별시 용산구 독서당로
1  경상남도 남해군 옥천로12길 302호
2       경상남도 김해시 가야로47길

In [126]:
# 셀 안에 리스트가 조냊하는 구조를 원하지 않으면 expand=True로 결과를 데이터 프레임으로 확장함
df['주소'].str.split(' ', expand=True)

       0    1       2     3
0  서울특별시  용산구    독서당로  None
1   경상남도  남해군  옥천로12길  302호
2   경상남도  김해시  가야로47길  None

In [127]:
df[['광역시도명', '시군구명']] = df['주소'].str.split(' ', expand=True)[[0, 1]]
df

                     주소  광역시도명 시군구명
0        서울특별시 용산구 독서당로  서울특별시  용산구
1  경상남도 남해군 옥천로12길 302호   경상남도  남해군
2       경상남도 김해시 가야로47길   경상남도  김해시

### 10.2.5 문자열 치환하기

In [128]:
data1 = {'col1': ['cat01', 'cat02', 'pig03'], 'col2': ['cat', 'cat', 'pig'],
         'col3': ['1,234', '1,456,234', '67,890']}
df = pd.DataFrame(data1)
df

    col1 col2       col3
0  cat01  cat      1,234
1  cat02  cat  1,456,234
2  pig03  pig     67,890

In [129]:
df['col1'].str.replace('cat','dog')

0    dog01
1    dog02
2    pig03
Name: col1, dtype: object

In [130]:
df['col3'].str.replace(',', '').astype('int')

0       1234
1    1456234
2      67890
Name: col3, dtype: int64

In [131]:
df['col1'].str.replace('cat','dog', regex=True)

0    dog01
1    dog02
2    pig03
Name: col1, dtype: object

### 10.2.6 문자열 포함 여부 확인하기

In [132]:
import pandas as pd
s = pd.Series(['cat01', 'cat02', 'dog01', '03cat', '01cow'])
s

0    cat01
1    cat02
2    dog01
3    03cat
4    01cow
dtype: object

In [133]:
s.str.contains('cat')

0     True
1     True
2    False
3     True
4    False
dtype: bool

In [134]:
s[s.str.contains('cat')]

0    cat01
1    cat02
3    03cat
dtype: object

In [135]:
s.str.startswith('cat')

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [136]:
s.str.endswith('cat')

0    False
1    False
2    False
3     True
4    False
dtype: bool

### 10.2.7 문자열 추출하기

In [137]:
s.str.extract('(cat)')

     0
0  cat
1  cat
2  NaN
3  cat
4  NaN

추출할 문자열을 따옴표 안에서 소괄호로 묶어야 하며 그렇지 않으면 ValueError가 발생함\
정규 표현식에서 하나의 소괄호는 하나의 캡처 그룹으로 간주되어 하나의 열을 가진 데이터 프레임을 반환함\
복수의 소괄호를 활용하여 복수의 캡쳐 그룹을 지정하면, 복수의 열을 가진 데이터 프레임이 반환됨

## 10.3 정규 표현식
저장소의 regex 마크다운 파일 참조