# chapter 8. 열 가공하기
## 8.1 열 가공하기
### 8.1.1 열 가공하기란?
열 가공하기는 데이터 전처리 과정에서 새로운 관측치를 추가하지 않고 주어진 데이터를 업무에 더 효율적인 데이터로 만드는 과정\
원시 데이터에서 행은 각 사례(instacne)를 의미하고, 열은 주로 데이터의 특성(feature)를 의미함\
독립변인이나 종속변인으로 사용되는 것이 특성임\
안타와 홈런이라는 특성으로는 적중률 특성과 관계가 높은 특성을 찾지 못하였는데, 타수와 안타라는 특성을 이용해 새로운 특성인 타율을 생성하니 적중률과 관계가 높은 특성을 찾을 수 있었다면, 데이터 전처리 과정에서 추가 데이터 수집 없이 주어진 데이터를 더 적합한 데이터로 만들었다고 할 수 있으며 이를 열 가공하기라고 함

### 8.1.2 다양한 열 가공하기 소개
각 열의 연산을 하거나 통계 함수를 사용하거나 불리언 마스킹과 데이터의 범주화로도 새로운 특성을 만드는 열 가공하기를 수행할 수 있음

## 8.2 다양한 연산으로 열 가공하기
### 8.2.1 객체 간 연산으로 열 가공하기

In [1]:
import pandas as pd
data1 = [['A', 0.1, 50, 0, 5], ['B', 0.25, 400, 40, 99],
         ['C', 0.35, 100, 10, 36], ['D', 0.3, 300, 4, 91]]
df1 = pd.DataFrame(data1, columns=['선수', '적중률', '타수', '홈런', '안타'])
df1

  선수   적중률   타수  홈런  안타
0  A  0.10   50   0   5
1  B  0.25  400  40  99
2  C  0.35  100  10  36
3  D  0.30  300   4  91

In [2]:
df1['타율'] = df1['안타'] / df1['타수']
df1

  선수   적중률   타수  홈런  안타        타율
0  A  0.10   50   0   5  0.100000
1  B  0.25  400  40  99  0.247500
2  C  0.35  100  10  36  0.360000
3  D  0.30  300   4  91  0.303333

### 8.2.2 객체 내 연산으로 열 가공하기

In [3]:
data2 = [[10, 0, 20], [30, 30, 40], [0, 20, 10], [30, 10, 10]]
idx = ['2024-05-01', '2024-05-02', '2024-05-03', '2024-05-04']
df2 = pd.DataFrame(data2, index=idx, columns=['A품목', 'B품목', 'C품목'])
df2

            A품목  B품목  C품목
2024-05-01   10    0   20
2024-05-02   30   30   40
2024-05-03    0   20   10
2024-05-04   30   10   10

In [4]:
df2['일판매량'] = df2.sum(axis=1)
df2['누적판매'] = df2['일판매량'].cumsum()
df2

            A품목  B품목  C품목  일판매량  누적판매
2024-05-01   10    0   20    30    30
2024-05-02   30   30   40   100   130
2024-05-03    0   20   10    30   160
2024-05-04   30   10   10    50   210

### 8.2.3 수학적 연산으로 열 가공하기

In [5]:
df3 = pd.DataFrame([[1, 2], [2, 4], [3, 8], [4, 16]], columns=['x', 'y'])
df3

   x   y
0  1   2
1  2   4
2  3   8
3  4  16

In [6]:
import numpy as np
# pd.options.display.float_format = '{:.3f}'.format # 소수점 셋째 자리 출력
df3['log_y'] = np.log(df3['y'])
df3

   x   y     log_y
0  1   2  0.693147
1  2   4  1.386294
2  3   8  2.079442
3  4  16  2.772589

## 8.3 순위 매기기
수치형 데이터의 값보다 순위나 백분위수가 분석 목적에 더욱 적함할 때도 있으며 판다스의 rank 함수를 이용할 수 있음

### 8.3.1 순위 매기기(rank)
판다스 rank\
데이터 프레임이나 시리즈의 순위를 매기는 함수
```py
rank 함수의 주요 매개변수와 인수, 기본값
df.rank(method='average', ascending=True, pct=False)
```
* method : 동점자 처리 방식을 지정함
* ascending : 오름차순과 내림차순을 지정하며 기본값은 오름차순
* pct : 순위를 반환할지 백분위수(percentile)를 반환할지 지정하며 기본값이 False이기에 순위를 반환하며 True는 백분위수 반환

In [7]:
import pandas as pd
# pd.options.display.float_format = None # 소수점 출력 옵션 리셋
s = pd.Series([90, 70, 80, 60], index=list('ABCD'))
s

A    90
B    70
C    80
D    60
dtype: int64

In [8]:
s.rank()

A    4.0
B    2.0
C    3.0
D    1.0
dtype: float64

In [9]:
s.rank(ascending=False).astype('int')

A    1
B    3
C    2
D    4
dtype: int64

In [10]:
s.rank(pct=True)

A    1.00
B    0.50
C    0.75
D    0.25
dtype: float64

### 8.3.2 rank 함수의 다양한 동점자 처리 방식
|인수|동점자 처리 방식|
|:--|:--|
|'average'|평균 순위(두 명이 공등 1등일 때 모두 1.5등), 기본값|
|'min'|최저 순위(두 명이 공동 1등일 때 모두 1등)|
|'max'|최대 순위(두 명이 공동 1등일 때 모두 2등)|
|'first'|순서에 따른 순위(두 명이 공동 1등일 때 먼저 출현한 행이 1등)|
|'dense'|밀집한 순위('min'과 비슷하나 공동 1등이 존재해도 다음 순위로 2등을 부여)|

In [11]:
import pandas as pd
data = [['김판다', 82, 17], ['권보아', 95, 17], ['강승주', 95, 18],
        ['안지선', 72, 18], ['조민영', 72, 19], ['최진환', 95, 19]]
df = pd.DataFrame(data, columns=['이름', '점수', '나이'])
df

    이름  점수  나이
0  김판다  82  17
1  권보아  95  17
2  강승주  95  18
3  안지선  72  18
4  조민영  72  19
5  최진환  95  19

In [12]:
df['average'] = df['점수'].rank(ascending=False)
df['min'] = df['점수'].rank(ascending=False, method='min')
df['max'] = df['점수'].rank(ascending=False, method='max')
df['first'] = df['점수'].rank(ascending=False, method='first')
df['dense'] = df['점수'].rank(ascending=False, method='dense')
df

    이름  점수  나이  average  min  max  first  dense
0  김판다  82  17      4.0  4.0  4.0    4.0    2.0
1  권보아  95  17      2.0  1.0  3.0    1.0    1.0
2  강승주  95  18      2.0  1.0  3.0    2.0    1.0
3  안지선  72  18      5.5  5.0  6.0    5.0    3.0
4  조민영  72  19      5.5  5.0  6.0    6.0    3.0
5  최진환  95  19      2.0  1.0  3.0    3.0    1.0

## 8.4 불리언 마스킹
True, False에 따라 값을 부여하는 것이 불리언 마스킹(boolean masking)\
불리언 마스킹은 불(bool)에 따라 값을 씌운다(mask)는 의미\
기존에 수집된 데이터를 조건에 따라 새로운 값으로 만들어 유용한 열 가공 기법임

### 8.4.1 불리언 인덱싱으로 불리언 마스킹
불리언 인덱싱을 수행한 후 새로운 값을 배정하는 것은 가장 기본적인 형태의 불리언 마스킹임

In [13]:
import pandas as pd
data = {'국어': {'가': 86, '나': 79, '다': 93, '라': 80},
        '영어': {'가': 90, '나': 10, '다': 50, '라': 95}}
df = pd.DataFrame(data)
df

   국어  영어
가  86  90
나  79  10
다  93  50
라  80  95

In [14]:
df1 = df.copy()
df1.loc[df1['영어'] >= 90, '영어평점'] = 4.5
df1

   국어  영어  영어평점
가  86  90   4.5
나  79  10   NaN
다  93  50   NaN
라  80  95   4.5

### 8.4.2 판다스 함수로 불리언 마스킹(mask, where)
판다스 mask\
조건문이 True인 부분의 값을 변환하는 함수, 즉 불리언 마스킹을 수행하는 함수

판다스 where\
조건문이 False인 부분의 값을 변환하는 함수, 즉 불리언 마스킹을 수행하는 함수
```py
mask 함수의 주요 매개변수와 인수, 기본값
df.mask(cond, other=nan)
```
* cond : 조건문처럼 작동하는 True와 False의 배열을 입력함
* other : 조건문이 True일 때 변환될 값을 지정하며 기본값은 NaN

mask와 where 함수는 시리즈와 데이터 프레임에 모두 적용됨\
주로 시리즈에 적용하므로 시리즈를 대상으로 실습할 것임\
mask 함수를 적용하고 조건문을 입력하면 입력된 조건문이 True인 위치가 NaN으로 변환되며 where 함수는 조건문이 False인 위치가 NaN으로 변환됨

In [15]:
df

   국어  영어
가  86  90
나  79  10
다  93  50
라  80  95

In [18]:
df['국어'].mask(df['국어'] < 80)

가    86.0
나     NaN
다    93.0
라    80.0
Name: 국어, dtype: float64

In [19]:
cond1 = df['국어'] < 80
df['국어'].where(cond1)

가     NaN
나    79.0
다     NaN
라     NaN
Name: 국어, dtype: float64

In [20]:
df['국어'].mask(~cond1)

가     NaN
나    79.0
다     NaN
라     NaN
Name: 국어, dtype: float64

In [21]:
df['국어'].mask(cond1, other='낙제')

가    86
나    낙제
다    93
라    80
Name: 국어, dtype: object

In [22]:
cond2 = df['영어'] >= 90
df['국어'].mask(cond2, df['국어'] + 2)

가    88
나    79
다    93
라    82
Name: 국어, dtype: int64

In [23]:
df['국어'].where(cond2).mean()

np.float64(83.0)

### 8.4.3 넘파이의 np.where 함수로 불리언 마스킹

In [24]:
df2 = df.copy()
df2['국어'].mask(cond1, '낙제').mask(~cond1, '이수')

가    이수
나    낙제
다    이수
라    이수
Name: 국어, dtype: object

mask 함수는 하나의 값을 부여할 때마다 mask 함수를 한 번 사용해야 하고, True와 False에 각각 값을 부여하기에 두 번의 mask 함수를 사용해야 하는 불편함이 존재함

넘파이 np.where\
True와 False에 따라 각각 값을 부여하는 함수
```py
np.where 함수의 주요 매개변수와 인수, 기본값
np.where(condition, x, y)
```
* condition : 불(bool)자료형 배열을 입력하는데, 즉 조건문을 입력받는 매개변수
* x : True일 때 부여할 값을 입력하며 단일 값 또는 배열을 입력함
* y : False일 때 부여할 값을 입력하며 단일 값 또는 배열을 입력함

In [25]:
import numpy as np
np.where(cond1, '낙제', '이수')

array(['이수', '낙제', '이수', '이수'], dtype='<U2')

In [26]:
df2['국어평가'] = np.where(cond1, '낙제', '이수')
df2

   국어  영어 국어평가
가  86  90   이수
나  79  10   낙제
다  93  50   이수
라  80  95   이수

### 8.4.4 넘파이의 np.select 함수로 불리언 마스킹
np.where 함수를 사용하면 True, False에 따라 각기 다른 두 개의 값이 편리하게 부여됨\
이번에는 조건에 따라 세 종류의 값을 부여해 보자\
국어가 90점 이상이면 A, 80점 이상이면 B, 80점 미만이면 C를 부여함

In [27]:
df3 = df.copy()
cond3 = df3['국어']>=90
cond4 = df3['국어']>=80

In [28]:
np.where(cond4, np.where(cond3, 'A', 'B'), 'C')

array(['B', 'C', 'A', 'B'], dtype='<U1')

In [29]:
df3['국어'].mask(cond3, 'A').mask(~cond3 & cond4, 'B').mask(~cond4, 'C')

가    B
나    C
다    A
라    B
Name: 국어, dtype: object

mask 함수를 세 번 사용하면 A, B, C의 학점이 부여됨\
더 많은 조건문으로 더 많은 종류의 값을 부여하면 코드가 복잡해지고 가독성이 떨어지며 코드의 작성도 어려워짐\
불리언 마스킹으로 3 종류 이상의 값을 반환할 때는 np.where, mask 함수 모두 불편한데 이때는 np.select 함수를 사용함

넘파이 np.select\
여러 개의 조건문을 입력해 각 조건에 해당하는 값을 반환하는 함수
```py
np.select(condlist, choicelist, default=0)
```
* condlist : 조건문들을 리스트로 묶어 입력함
* choicelist : 조건문을 만족할 때 반환할 값을 리스트로 묶어 입력함
* default : condlist의 모든 조건에서 False일 때 부여할 값을 지정함

np.select 함수는 불리언 마스킹 결과 여러 종류의 값을 반환해야 할 때 사용함\
매개변수 condlist에 조건문을 리스트로 묶어 입력하고, 매개변수 choicelist에 각 조건을 맞추어 반환해야 할 값들을 리스트로 묶어 입력하면 각 조건에 맞추어 지정한 값이 반환됨\
매개변수 default로 어느 조건에도 해당하지 않을 때 부여할 값도 설정할 수 있음

In [30]:
np.select([cond3, ~cond3&cond4], ['A','B'],'C')

array(['B', 'C', 'A', 'B'], dtype='<U1')

In [31]:
# cond3와 cond4를 모두 만족할 때는 더 왼쪽에 위치한 cond3의 값인 'A'를 부여하기에 이렇게 작성하여도 됨
np.select([cond3, cond4], ['A','B'],'C')

array(['B', 'C', 'A', 'B'], dtype='<U1')

In [33]:
df3['국어학점'] = np.select([cond3, cond4], ['A','B'],'C')
df3

   국어  영어 국어학점
가  86  90    B
나  79  10    C
다  93  50    A
라  80  95    B